<!DOCTYPE html>
<html>
<body>
<div align="center">
<h2>Prepared by Asif Bhat</h2>
<h1>Merging Dataframes</h1>
</div>
    
</body>
</html>

In [24]:
import numpy as np
import pandas as pd
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

### Merging Dataframes

In [25]:
emp1= pd.DataFrame({'empid':['E90','E87'],
                   'Name':['Asif','Basit']})
emp1


emp2= pd.DataFrame({'empid':['E22','E74','E90'],
                   'Name':['Minil','Akash','Asif']})
emp2


address= pd.DataFrame({'empid':['E87','E22','E49'], 
                   'City':['Mumbai','Banglore','Pune'] , 
                   'State':['Maharashtra','Karnataka','Maharashtra']})
address

  empid   Name
0   E90   Asif
1   E87  Basit

  empid   Name
0   E22  Minil
1   E74  Akash
2   E90   Asif

  empid      City        State
0   E87    Mumbai  Maharashtra
1   E22  Banglore    Karnataka
2   E49      Pune  Maharashtra

In [26]:
employees = pd.concat([emp1,emp2])
employees
employees = employees.reset_index(drop=True)
employees

  empid   Name
0   E90   Asif
1   E87  Basit
0   E22  Minil
1   E74  Akash
2   E90   Asif

  empid   Name
0   E90   Asif
1   E87  Basit
2   E22  Minil
3   E74  Akash
4   E90   Asif

In [27]:
#Concat Dataframes
# Method-1
employees = pd.concat([emp1,emp2])
employees
employees=employees.reset_index(drop=True)
employees

  empid   Name
0   E90   Asif
1   E87  Basit
0   E22  Minil
1   E74  Akash
2   E90   Asif

  empid   Name
0   E90   Asif
1   E87  Basit
2   E22  Minil
3   E74  Akash
4   E90   Asif

In [28]:
#Concat Dataframe
# Method-2
employees1 = emp1.append(emp2)
employees1
employees1=employees1.reset_index(drop=True)
employees1

AttributeError: 'DataFrame' object has no attribute 'append'

In [11]:
employees2= pd.concat([emp1,emp2],ignore_index=True)
employees2

  empid   Name
0   E90   Asif
1   E87  Basit
2   E22  Minil
3   E74  Akash
4   E90   Asif

In [13]:
DUPLIKAT = employees[employees.duplicated()]
DUPLIKAT

  empid  Name
4   E90  Asif

In [41]:
# Check for duplicates after concatenation
duplicates = employees[employees.duplicated()]
duplicates

  empid  Name
4   E90  Asif

In [42]:
# Remove duplicates
employees.drop_duplicates(keep='last',inplace=True)
employees

  empid   Name
1   E87  Basit
2   E22  Minil
3   E74  Akash
4   E90   Asif

In [43]:
employees.reset_index(drop=True,inplace=True)
employees

  empid   Name
0   E87  Basit
1   E22  Minil
2   E74  Akash
3   E90   Asif

In [44]:
employees
address

  empid   Name
0   E87  Basit
1   E22  Minil
2   E74  Akash
3   E90   Asif

  empid      City        State
0   E87    Mumbai  Maharashtra
1   E22  Banglore    Karnataka
2   E49      Pune  Maharashtra

#### Inner Join

<img src= 'innerjoin.PNG'>

In [14]:
INNIER = pd.merge(employees,address,on="empid")
INNIER

  empid   Name      City        State
0   E87  Basit    Mumbai  Maharashtra
1   E22  Minil  Banglore    Karnataka

In [15]:
kim = pd.merge(employees,address,on="empid",how='inner')
kim

  empid   Name      City        State
0   E87  Basit    Mumbai  Maharashtra
1   E22  Minil  Banglore    Karnataka

In [20]:
# Inner Join
inner = pd.merge(employees,address,on='empid')
inner

  empid   Name      City        State
0   E87  Basit    Mumbai  Maharashtra
1   E22  Minil  Banglore    Karnataka

In [21]:
# Inner Join
inner = pd.merge(employees,address,on='empid',how='inner')
inner

  empid   Name      City        State
0   E87  Basit    Mumbai  Maharashtra
1   E22  Minil  Banglore    Karnataka

#### Left Outer Join

<img src= 'leftouterjoin1.png'>

In [22]:
# Left Outer Join
left = pd.merge(employees,address,on='empid',how='left')
left

  empid   Name      City        State
0   E87  Basit    Mumbai  Maharashtra
1   E22  Minil  Banglore    Karnataka
2   E74  Akash       NaN          NaN
3   E90   Asif       NaN          NaN

#### Right Outer Join

<img src='rightouterjoin1.PNG'>

In [48]:
# Right Outer Join
right = pd.merge(employees,address,on='empid',how='right')
right

  empid   Name      City        State
0   E87  Basit    Mumbai  Maharashtra
1   E22  Minil  Banglore    Karnataka
2   E49    NaN      Pune  Maharashtra

#### Full Outer Join

<img src= 'fullouterjoin1.png'>

In [24]:
employees
address

  empid   Name
0   E87  Basit
1   E22  Minil
2   E74  Akash
3   E90   Asif

  empid      City        State
0   E87    Mumbai  Maharashtra
1   E22  Banglore    Karnataka
2   E49      Pune  Maharashtra

In [20]:
#Full outer join
full = pd.merge(employees,address,how='outer',on='empid')
full

  empid   Name      City        State
0   E22  Minil  Banglore    Karnataka
1   E49    NaN      Pune  Maharashtra
2   E74  Akash       NaN          NaN
3   E87  Basit    Mumbai  Maharashtra
4   E90   Asif       NaN          NaN
5   E90   Asif       NaN          NaN

In [19]:
# Salary Data
sal = pd.DataFrame({'empid':['E87','E22','E74','E90','E49'],
                    'salary':['$10,000','$30,000','$20,000','$60,000','$90,000']})
sal

  empid   salary
0   E87  $10,000
1   E22  $30,000
2   E74  $20,000
3   E90  $60,000
4   E49  $90,000

In [21]:
# Add Salary details ( Merge sal & full dataframes)
employee_details = pd.merge(full,sal,on='empid')
employee_details

  empid   Name      City        State   salary
0   E22  Minil  Banglore    Karnataka  $30,000
1   E49    NaN      Pune  Maharashtra  $90,000
2   E74  Akash       NaN          NaN  $20,000
3   E87  Basit    Mumbai  Maharashtra  $10,000
4   E90   Asif       NaN          NaN  $60,000
5   E90   Asif       NaN          NaN  $60,000

In [22]:
exp1 = pd.DataFrame({'employee_id':['1','2','3'],'employee_name':['Emin','Ferid','Tural']})
exp1

  employee_id employee_name
0           1          Emin
1           2         Ferid
2           3         Tural

In [30]:
# Employee experience
exp = pd.DataFrame({'employee_id':['E87','E22','E74','E90','E49'],
                    'experience':['5 years','3 years','7 years','2 years','10 years']})
exp

  employee_id experience
0         E87    5 years
1         E22    3 years
2         E74    7 years
3         E90    2 years
4         E49   10 years

In [29]:
# Add employee experinece using merge()
# As column names are different (empid , employee_id) we have to use left_on & right_on parameter
pd.merge(employee_details,exp,left_on=['empid'],right_on=['employee_id'],how='inner')

  empid   Name      City        State   salary employee_id experience
0   E87  Basit    Mumbai  Maharashtra  $10,000         E87    5 years
1   E22  Minil  Banglore    Karnataka  $30,000         E22    3 years
2   E74  Akash       NaN          NaN  $20,000         E74    7 years
3   E90   Asif       NaN          NaN  $60,000         E90    2 years
4   E49    NaN      Pune  Maharashtra  $90,000         E49   10 years

In [32]:
# Add employee experinece using merge() and drop the duplicate column (employee_id)
pd.merge(employee_details,exp,
         left_on=['empid'],
         right_on=['employee_id'],
        how='inner').drop('employee_id',axis=1)

  empid   Name      City        State   salary experience
0   E22  Minil  Banglore    Karnataka  $30,000    3 years
1   E49    NaN      Pune  Maharashtra  $90,000   10 years
2   E74  Akash       NaN          NaN  $20,000    7 years
3   E87  Basit    Mumbai  Maharashtra  $10,000    5 years
4   E90   Asif       NaN          NaN  $60,000    2 years
5   E90   Asif       NaN          NaN  $60,000    2 years

In [31]:
#Save the dataframe
employee_details=pd.merge(employee_details,exp,
                          left_on=['empid'],
                          right_on=['employee_id'],
                          how='inner').drop('employee_id',axis=1)
employee_details

  empid   Name      City        State   salary experience
0   E87  Basit    Mumbai  Maharashtra  $10,000    5 years
1   E22  Minil  Banglore    Karnataka  $30,000    3 years
2   E74  Akash       NaN          NaN  $20,000    7 years
3   E90   Asif       NaN          NaN  $60,000    2 years
4   E49    NaN      Pune  Maharashtra  $90,000   10 years

# End