<!DOCTYPE html>
<html>
<body>
<div align="center">
    
<h1>Pandas - Series & Dataframes</h1>


</div>
</body>
</html>

In [35]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import glob
import re
import math

In [36]:
import warnings
warnings.filterwarnings("ignore")

# Series

## Create Series

In [37]:
# Create series from Nump Array
v = np.array([1,2,3,4,5,6,7])
s1 = pd.Series(v)
s1

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int32

In [38]:
#Datatype of Series
s1.dtype

dtype('int32')

In [39]:
# number of bytes allocated to each item
s1.values.itemsize

4

In [40]:
# Number of bytes consumed by Series
s1.nbytes

28

In [41]:
# Shape of the Series
s1.shape

(7,)

In [42]:
# number of dimensions
s1.ndim

1

In [43]:
# Length of Series
len(s1)

7

In [44]:
s1.count()

7

In [45]:
s1.size

7

In [46]:
# Create series from List 
s0 = pd.Series([1,2,3],index = ['a','b','c'])
s0

a    1
b    2
c    3
dtype: int64

In [47]:
# Modifying index in Series
s1.index = ['a' , 'b' , 'c' , 'd' , 'e' , 'f' , 'g']
s1

a    1
b    2
c    3
d    4
e    5
f    6
g    7
dtype: int32

In [48]:
# Create Series using Random and Range function
v2 = np.random.random(10)
ind2 = np.arange(0,10)
s = pd.Series(v2,ind2)
v2 , ind2 , s

(array([0.11318566, 0.43269519, 0.38180402, 0.58853078, 0.23698119,
        0.96613917, 0.80537636, 0.46869747, 0.56842918, 0.8822425 ]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 0    0.113186
 1    0.432695
 2    0.381804
 3    0.588531
 4    0.236981
 5    0.966139
 6    0.805376
 7    0.468697
 8    0.568429
 9    0.882243
 dtype: float64)

In [49]:
# Creating Series from Dictionary
dict1 = {'a1' :10 , 'a2' :20 , 'a3':30 , 'a4':40}
s3 = pd.Series(dict1)
s3

a1    10
a2    20
a3    30
a4    40
dtype: int64

In [50]:
pd.Series(99, index=[0, 1, 2, 3, 4, 5, 6, 7])

0    99
1    99
2    99
3    99
4    99
5    99
6    99
7    99
dtype: int64

## Slicing Series

In [51]:
s

0    0.113186
1    0.432695
2    0.381804
3    0.588531
4    0.236981
5    0.966139
6    0.805376
7    0.468697
8    0.568429
9    0.882243
dtype: float64

In [52]:
# Return all elements of the series
s[:]

0    0.113186
1    0.432695
2    0.381804
3    0.588531
4    0.236981
5    0.966139
6    0.805376
7    0.468697
8    0.568429
9    0.882243
dtype: float64

In [53]:
# First three element of the Series
s[0:3]

0    0.113186
1    0.432695
2    0.381804
dtype: float64

In [54]:
# Last element of the Series
s[-1:]

9    0.882243
dtype: float64

In [55]:
# Fetch first 4 elements in a series
s[:4]

0    0.113186
1    0.432695
2    0.381804
3    0.588531
dtype: float64

In [56]:
# Return all elements of the series except last two elements.
s[:-2]

0    0.113186
1    0.432695
2    0.381804
3    0.588531
4    0.236981
5    0.966139
6    0.805376
7    0.468697
dtype: float64

In [57]:
# Return all elements of the series except last element.
s[:-1]

0    0.113186
1    0.432695
2    0.381804
3    0.588531
4    0.236981
5    0.966139
6    0.805376
7    0.468697
8    0.568429
dtype: float64

In [58]:
# Return last two elements of the series
s[-2:]

8    0.568429
9    0.882243
dtype: float64

In [59]:
# # Return last element of the series
s[-1:]

9    0.882243
dtype: float64

In [60]:
s[-3:-1]

7    0.468697
8    0.568429
dtype: float64

## Append Series

In [61]:
s2 = s1.copy()
s2

a    1
b    2
c    3
d    4
e    5
f    6
g    7
dtype: int32

In [62]:
s3

a1    10
a2    20
a3    30
a4    40
dtype: int64

In [63]:
# Append S2 & S3 Series
s4 = s2.append(s3)
s4

AttributeError: 'Series' object has no attribute 'append'

In [30]:
# When "inplace=False" it will return a new copy of data with the operation performed
s4.drop('a4' , inplace=False)

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
dtype: int64

In [31]:
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
a4    40
dtype: int64

In [32]:
# When we use "inplace=True" it will affect the dataframe
s4.drop('a4', inplace=True)
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
dtype: int64

In [33]:
s4 = s4.append(pd.Series({'a4': 7}))
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
a4     7
dtype: int64

## Operation on Series

In [34]:
v1 = np.array([10,20,30])
v2 = np.array([1,2,3])
s1 = pd.Series(v1) 
s2 = pd.Series(v2)
s1 , s2

(0    10
 1    20
 2    30
 dtype: int32,
 0    1
 1    2
 2    3
 dtype: int32)

In [35]:
# Addition of two series
s1.add(s2)

0    11
1    22
2    33
dtype: int32

In [36]:
# Subtraction of two series
s1.sub(s2)

0     9
1    18
2    27
dtype: int32

In [37]:
# Subtraction of two series
s1.subtract(s2)

0     9
1    18
2    27
dtype: int32

In [38]:
# Increment all numbers in a series by 9
s1.add(9)

0    19
1    29
2    39
dtype: int32

In [39]:
# Multiplication of two series
s1.mul(s2)

0    10
1    40
2    90
dtype: int32

In [40]:
# Multiplication of two series
s1.multiply(s2)

0    10
1    40
2    90
dtype: int32

In [41]:
# Multiply each element by 1000
s1.multiply(1000)

0    10000
1    20000
2    30000
dtype: int32

In [31]:
# Division
s1.divide(s2)

a    1.0
b    1.0
c    1.0
d    1.0
e    1.0
f    1.0
g    1.0
dtype: float64

In [43]:
# Division
s1.div(s2)

0    10.0
1    10.0
2    10.0
dtype: float64

In [44]:
# MAX number in a series
s1.max()

30

In [45]:
# Min number in a series
s1.min()

10

In [46]:
# Average
s1.mean()

20.0

In [47]:
# Median
s1.median()

20.0

In [48]:
# Standard Deviation
s1.std()

10.0

In [49]:
# Series comparison
s1.equals(s2)

False

In [50]:
s4 =s1

In [51]:
# Series comparison
s1.equals(s4)

True

In [52]:
s5 = pd.Series([1,1,2,2,3,3], index=[0, 1, 2, 3, 4, 5])
s5

0    1
1    1
2    2
3    2
4    3
5    3
dtype: int64

In [53]:
s5.value_counts()

1    2
2    2
3    2
dtype: int64

# DataFrame

## Create DataFrame

In [77]:
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [32]:
# Create Dataframe using List
lang = ['Java' , 'Python' , 'C' , 'C++']
df = pd.DataFrame(lang)
df

        0
0    Java
1  Python
2       C
3     C++

In [33]:
# Add column in the Dataframe
rating = [1,2,3,4]
df[1] = rating
df

        0  1
0    Java  1
1  Python  2
2       C  3
3     C++  4

In [80]:
df.columns = ['Language','Rating']

In [81]:
df

  Language  Rating
0     Java       1
1   Python       2
2        C       3
3      C++       4

In [34]:
# Create Dataframe from Dictionary

data = [{'a': 1, 'b': 2},{'a': 5, 'b': 10, 'c': 20}]

df2 = pd.DataFrame(data)
df3 = pd.DataFrame(data, index=['row1', 'row2'], columns=['a', 'b'])
df4 = pd.DataFrame(data, index=['row1', 'row2'], columns=['a', 'b' ,'c'])
df5 = pd.DataFrame(data, index=['row1', 'row2'], columns=['a', 'b' ,'c' , 'd'])

In [35]:
df2

   a   b     c
0  1   2   NaN
1  5  10  20.0

In [36]:
df3

      a   b
row1  1   2
row2  5  10

In [62]:
df4

      a   b     c
row1  1   2   NaN
row2  5  10  20.0

In [63]:
df5

      a   b     c   d
row1  1   2   NaN NaN
row2  5  10  20.0 NaN

In [64]:
df5[4] = ('e')
df5

      a   b     c   d  4
row1  1   2   NaN NaN  e
row2  5  10  20.0 NaN  e

In [65]:
df = df.pop
df

<bound method DataFrame.pop of   Language  Rating
0     Java       1
1   Python       2
2        C       3
3      C++       4>

In [66]:
# Create Dataframe from Dictionary
df0 = pd.DataFrame({'ID' :[1,2,3,4] , 'Name' :['Asif' , 'Basit' , 'Ross' , 'John']})
df0

   ID   Name
0   1   Asif
1   2  Basit
2   3   Ross
3   4   John

In [67]:
# Create a DataFrame from Dictionary of Series
dict = {'A' : pd.Series([1, 2, 3],    index=['a', 'b', 'c']),
        'B' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}

df1 = pd.DataFrame(dict)
df1

     A  B
a  1.0  1
b  2.0  2
c  3.0  3
d  NaN  4

#### Dataframe of Random Numbers with Date Indices

In [68]:
dates = pd.date_range(start='2020-01-20', end='2020-01-26')
dates

DatetimeIndex(['2020-01-20', '2020-01-21', '2020-01-22', '2020-01-23',
               '2020-01-24', '2020-01-25', '2020-01-26'],
              dtype='datetime64[ns]', freq='D')

In [69]:
dates = pd.date_range('today',periods= 7)
dates

DatetimeIndex(['2022-07-18 21:04:53.411777', '2022-07-19 21:04:53.411777',
               '2022-07-20 21:04:53.411777', '2022-07-21 21:04:53.411777',
               '2022-07-22 21:04:53.411777', '2022-07-23 21:04:53.411777',
               '2022-07-24 21:04:53.411777'],
              dtype='datetime64[ns]', freq='D')

In [70]:
dates = pd.date_range(start='2020-01-20', periods=7)
dates

DatetimeIndex(['2020-01-20', '2020-01-21', '2020-01-22', '2020-01-23',
               '2020-01-24', '2020-01-25', '2020-01-26'],
              dtype='datetime64[ns]', freq='D')

In [71]:
M = np.random.random((7,7))
M

array([[0.03605484, 0.26193821, 0.26182009, 0.26445867, 0.44102698,
        0.60538618, 0.65613195],
       [0.51098396, 0.51201285, 0.46500688, 0.023028  , 0.54091948,
        0.64971654, 0.28195257],
       [0.32038716, 0.08886187, 0.36389985, 0.8057003 , 0.14284371,
        0.91043901, 0.6743519 ],
       [0.51800469, 0.18813725, 0.52334879, 0.35354907, 0.02726653,
        0.53962237, 0.87998026],
       [0.51019374, 0.3268585 , 0.69664867, 0.56099767, 0.07810533,
        0.81129177, 0.87620385],
       [0.02006634, 0.49278934, 0.54821355, 0.88104063, 0.34022179,
        0.18847439, 0.46548146],
       [0.4334954 , 0.33640973, 0.50354813, 0.86539347, 0.40839113,
        0.98542376, 0.9413105 ]])

In [72]:
dframe = pd.DataFrame(M , index=dates)
dframe

,0,1,2,3,4,5,6
2020-01-20,0.036055,0.261938,0.261820,0.264459,0.441027,0.605386,0.656132
2020-01-21,0.510984,0.512013,0.465007,0.023028,0.540919,0.649717,0.281953
2020-01-22,0.320387,0.088862,0.363900,0.805700,0.142844,0.910439,0.674352
2020-01-23,0.518005,0.188137,0.523349,0.353549,0.027267,0.539622,0.879980
2020-01-24,0.510194,0.326859,0.696649,0.560998,0.078105,0.811292,0.876204
2020-01-25,0.020066,0.492789,0.548214,0.881041,0.340222,0.188474,0.465481
2020-01-26,0.433495,0.336410,0.503548,0.865393,0.408391,0.985424,0.941310

In [73]:
#Changing Column Names
dframe.columns = ['C1' , 'C2' , 'C3', 'C4', 'C5', 'C6', 'C7']
dframe

,C1,C2,C3,C4,C5,C6,C7
2020-01-20,0.036055,0.261938,0.261820,0.264459,0.441027,0.605386,0.656132
2020-01-21,0.510984,0.512013,0.465007,0.023028,0.540919,0.649717,0.281953
2020-01-22,0.320387,0.088862,0.363900,0.805700,0.142844,0.910439,0.674352
2020-01-23,0.518005,0.188137,0.523349,0.353549,0.027267,0.539622,0.879980
2020-01-24,0.510194,0.326859,0.696649,0.560998,0.078105,0.811292,0.876204
2020-01-25,0.020066,0.492789,0.548214,0.881041,0.340222,0.188474,0.465481
2020-01-26,0.433495,0.336410,0.503548,0.865393,0.408391,0.985424,0.941310

In [ ]:
# List Index
dframe.index

In [ ]:
# List Column Names
dframe.columns

In [ ]:
# Datatype of each column
dframe.dtypes

In [ ]:
# Sort Dataframe by Column 'C1' in Ascending Order
dframe.sort_values(by='C1')

In [ ]:
# Sort Dataframe by Column 'C1' in Descending Order
dframe.sort_values(by='C1' , ascending=False)

## Delete Column in DataFrame

In [ ]:
df1

In [ ]:
# Delete Column using "del" function
del df1['B']

In [ ]:
df1

In [ ]:
df5

In [ ]:
# Delete Column using pop()
df5.pop('c')

In [ ]:
df5

In [ ]:
dict = {'A' : pd.Series([1, 2, 3,11],    index=['a', 'b', 'c','d']),
        'B' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}

df12 = pd.DataFrame(dict)
df12

In [ ]:
df12.drop(['A'], axis=1,inplace=True)
df12

## Delete Rows in DataFrame

In [ ]:
col1 = np.linspace(10, 100, 30)
col2 = np.random.randint(10,100,30)
df10 = pd.DataFrame({"C1" : col1 , "C2" :col2})
df10

In [ ]:
# Delete rows with index values 17,18,19
df10 = df10.drop([17,18,19], axis=0)
df10

In [ ]:
# Delete rows with index values 16 without using assignment operation
df10.drop([16], axis=0,inplace=True)
df10

In [ ]:
df10.drop(df10.index[5] , inplace=True)
df10

In [ ]:
#Delete first three rows
df10 = df10.iloc[3:,]
df10

In [ ]:
#Delete last four rows
df10 = df10.iloc[:-4,]
df10

In [ ]:
#Keep top 10 rows
df10 = df10.iloc[:10,]
df10

In [ ]:
df10

In [ ]:
df10.index[df10['C2'] == 56].tolist()

In [ ]:
df10

In [ ]:
# Delete row based on Column value
df10.drop(df10.index[df10['C2'] == 59].tolist() , axis=0,inplace=True)
df10

In [ ]:
# Delete row based on Column value
df10 = df10.drop(df10[df10["C2"]==46].index)
df10

In [ ]:
# Delete all rows with column C2 value 88
df10 = df10[df10.C2 != 88]
df10

In [ ]:
# Delete all rows with column C2 value 22 & 36 using isin operator
df10 = df10[~(df10.C2.isin ([22,36]))]
df10

In [ ]:
# Keep all rows with column C2 value 10,89,31 & 64 using isin operator
df10 = df10[df10.C2.isin ([42,76])]
df10

In [ ]:
dict = {'A' : pd.Series([1, 2, 3,11],    index=['a', 'b', 'c','d']),
        'B' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}

df11 = pd.DataFrame(dict)
df11

In [ ]:
#Delete all rows with label "d"
df11.drop("d", axis=0,inplace=True)
df11

In [ ]:
df13 = pd.DataFrame({ 'ID' :[1,2,3,4] , 
                     'Name' :['Asif' , 'Basit' , 'Ross' , 'John'] , 
                     'location' : ['India' , 'Australia','UK' , 'US'] })
df13

In [ ]:
ind = df13[((df13.Name == 'Ross') &(df13.ID == 3) & (df13.location == 'UK'))].index
df13.drop(ind,inplace=True)
df13

## Data Selection in Dataframe

In [82]:
df

  Language  Rating
0     Java       1
1   Python       2
2        C       3
3      C++       4

In [83]:
df.index = [1,2,3,4]
df

  Language  Rating
1     Java       1
2   Python       2
3        C       3
4      C++       4

In [84]:
# Data selection using row label
df.loc[1]

Language    Java
Rating         1
Name: 1, dtype: object

In [85]:
# Data selection using position (Integer Index based)
df.iloc[1]

Language    Python
Rating           2
Name: 2, dtype: object

In [86]:
df.loc[1:2]

  Language  Rating
1     Java       1
2   Python       2

In [87]:
df.iloc[1:2]

  Language  Rating
2   Python       2

In [88]:
# Data selection based on Condition
df.loc[df.Rating > 2]

  Language  Rating
3        C       3
4      C++       4

In [89]:
df1

     A  B
a  1.0  1
b  2.0  2
c  3.0  3
d  NaN  4

In [90]:
# Row & Column label based selection
df1.loc['a']

A    1.0
B    1.0
Name: a, dtype: float64

In [91]:
df1.iloc['a'] # This will throw error because iloc will not work on labels

TypeError: Cannot index by location index with a non-integer key

In [92]:
dframe

,C1,C2,C3,C4,C5,C6,C7
2020-01-20,0.036055,0.261938,0.261820,0.264459,0.441027,0.605386,0.656132
2020-01-21,0.510984,0.512013,0.465007,0.023028,0.540919,0.649717,0.281953
2020-01-22,0.320387,0.088862,0.363900,0.805700,0.142844,0.910439,0.674352
2020-01-23,0.518005,0.188137,0.523349,0.353549,0.027267,0.539622,0.879980
2020-01-24,0.510194,0.326859,0.696649,0.560998,0.078105,0.811292,0.876204
2020-01-25,0.020066,0.492789,0.548214,0.881041,0.340222,0.188474,0.465481
2020-01-26,0.433495,0.336410,0.503548,0.865393,0.408391,0.985424,0.941310

In [93]:
# Data selection using Row Label
dframe['2020-01-20' : '2020-01-22' ]

,C1,C2,C3,C4,C5,C6,C7
2020-01-20,0.036055,0.261938,0.261820,0.264459,0.441027,0.605386,0.656132
2020-01-21,0.510984,0.512013,0.465007,0.023028,0.540919,0.649717,0.281953
2020-01-22,0.320387,0.088862,0.363900,0.805700,0.142844,0.910439,0.674352

In [94]:
dframe.head(3)

,C1,C2,C3,C4,C5,C6,C7
2020-01-20,0.036055,0.261938,0.261820,0.264459,0.441027,0.605386,0.656132
2020-01-21,0.510984,0.512013,0.465007,0.023028,0.540919,0.649717,0.281953
2020-01-22,0.320387,0.088862,0.363900,0.805700,0.142844,0.910439,0.674352

In [96]:
# Selecting all rows & selected columns
dframe.loc[:,['C1' , 'C7']]

                  C1        C7
2020-01-20  0.036055  0.656132
2020-01-21  0.510984  0.281953
2020-01-22  0.320387  0.674352
2020-01-23  0.518005  0.879980
2020-01-24  0.510194  0.876204
2020-01-25  0.020066  0.465481
2020-01-26  0.433495  0.941310

In [97]:
#row & column label based selection
dframe.loc['2020-01-20' : '2020-01-22',['C1' , 'C7']]

                  C1        C7
2020-01-20  0.036055  0.656132
2020-01-21  0.510984  0.281953
2020-01-22  0.320387  0.674352

In [98]:
# Data selection based on Condition
dframe[dframe['C1'] > 0.5]

,C1,C2,C3,C4,C5,C6,C7
2020-01-21,0.510984,0.512013,0.465007,0.023028,0.540919,0.649717,0.281953
2020-01-23,0.518005,0.188137,0.523349,0.353549,0.027267,0.539622,0.879980
2020-01-24,0.510194,0.326859,0.696649,0.560998,0.078105,0.811292,0.876204

In [101]:
# Data selection based on Condition
dframe[(dframe['C1'] > 0.5) & (dframe['C4'] > 0.5)]

,C1,C2,C3,C4,C5,C6,C7
2020-01-24,0.510194,0.326859,0.696649,0.560998,0.078105,0.811292,0.876204

In [102]:
# Data selection using position (Integer Index based)
dframe.iloc[0][0]

0.03605483624634642

In [103]:
# Select all rows & first three columns
dframe.iloc[:,0:3]

                  C1        C2        C3
2020-01-20  0.036055  0.261938  0.261820
2020-01-21  0.510984  0.512013  0.465007
2020-01-22  0.320387  0.088862  0.363900
2020-01-23  0.518005  0.188137  0.523349
2020-01-24  0.510194  0.326859  0.696649
2020-01-25  0.020066  0.492789  0.548214
2020-01-26  0.433495  0.336410  0.503548

In [104]:
dframe.iloc[0][0] = 10

In [105]:
dframe.iloc[0][0]

10.0

In [106]:
# Display all rows where C1 has value of 10 or 20
dframe[dframe['C1'].isin([10,20])]

              C1        C2       C3        C4        C5        C6        C7
2020-01-20  10.0  0.261938  0.26182  0.264459  0.441027  0.605386  0.656132

## Set Value

In [107]:
# Set value of 888 for all elements in column 'C1'
dframe['C1'] = 888
dframe

             C1        C2        C3        C4        C5        C6        C7
2020-01-20  888  0.261938  0.261820  0.264459  0.441027  0.605386  0.656132
2020-01-21  888  0.512013  0.465007  0.023028  0.540919  0.649717  0.281953
2020-01-22  888  0.088862  0.363900  0.805700  0.142844  0.910439  0.674352
2020-01-23  888  0.188137  0.523349  0.353549  0.027267  0.539622  0.879980
2020-01-24  888  0.326859  0.696649  0.560998  0.078105  0.811292  0.876204
2020-01-25  888  0.492789  0.548214  0.881041  0.340222  0.188474  0.465481
2020-01-26  888  0.336410  0.503548  0.865393  0.408391  0.985424  0.941310

In [108]:
# Set value of 777 for first three rows in Column 'C6'
dframe.at[0:3,'C6'] = 777

In [110]:
dframe.round(2)

             C1    C2    C3    C4    C5      C6    C7
2020-01-20  888  0.26  0.26  0.26  0.44  777.00  0.66
2020-01-21  888  0.51  0.47  0.02  0.54  777.00  0.28
2020-01-22  888  0.09  0.36  0.81  0.14  777.00  0.67
2020-01-23  888  0.19  0.52  0.35  0.03    0.54  0.88
2020-01-24  888  0.33  0.70  0.56  0.08    0.81  0.88
2020-01-25  888  0.49  0.55  0.88  0.34    0.19  0.47
2020-01-26  888  0.34  0.50  0.87  0.41    0.99  0.94

In [111]:
# Set value of 333 in first row and third column
dframe.iat[0,2] = 333

In [112]:
dframe

,C1,C2,C3,C4,C5,C6,C7
2020-01-20,888,0.261938,333.000000,0.264459,0.441027,777.000000,0.656132
2020-01-21,888,0.512013,0.465007,0.023028,0.540919,777.000000,0.281953
2020-01-22,888,0.088862,0.363900,0.805700,0.142844,777.000000,0.674352
2020-01-23,888,0.188137,0.523349,0.353549,0.027267,0.539622,0.879980
2020-01-24,888,0.326859,0.696649,0.560998,0.078105,0.811292,0.876204
2020-01-25,888,0.492789,0.548214,0.881041,0.340222,0.188474,0.465481
2020-01-26,888,0.336410,0.503548,0.865393,0.408391,0.985424,0.941310

In [113]:
dframe.iloc[0,2] = 555
dframe

,C1,C2,C3,C4,C5,C6,C7
2020-01-20,888,0.261938,555.000000,0.264459,0.441027,777.000000,0.656132
2020-01-21,888,0.512013,0.465007,0.023028,0.540919,777.000000,0.281953
2020-01-22,888,0.088862,0.363900,0.805700,0.142844,777.000000,0.674352
2020-01-23,888,0.188137,0.523349,0.353549,0.027267,0.539622,0.879980
2020-01-24,888,0.326859,0.696649,0.560998,0.078105,0.811292,0.876204
2020-01-25,888,0.492789,0.548214,0.881041,0.340222,0.188474,0.465481
2020-01-26,888,0.336410,0.503548,0.865393,0.408391,0.985424,0.941310

In [114]:
# Create Copy of the calling objects data along with indices.
# Modifications to the data or indices of the copy will not be reflected in the original object 
dframe1 = dframe.copy(deep=True)

In [115]:
dframe1[(dframe1['C1'] > 0.5) & (dframe1['C4'] > 0.5)] = 0

In [116]:
dframe1[dframe1['C1'] == 0]

            C1   C2   C3   C4   C5   C6   C7
2020-01-22   0  0.0  0.0  0.0  0.0  0.0  0.0
2020-01-24   0  0.0  0.0  0.0  0.0  0.0  0.0
2020-01-25   0  0.0  0.0  0.0  0.0  0.0  0.0
2020-01-26   0  0.0  0.0  0.0  0.0  0.0  0.0

In [119]:
# Replace zeros in Column C1 with 99
dframe1[dframe1['C1'].isin([0])] = 99
dframe1

,C1,C2,C3,C4,C5,C6,C7
2020-01-20,888,0.261938,555.000000,0.264459,0.441027,777.000000,0.656132
2020-01-21,888,0.512013,0.465007,0.023028,0.540919,777.000000,0.281953
2020-01-22,99,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000
2020-01-23,888,0.188137,0.523349,0.353549,0.027267,0.539622,0.879980
2020-01-24,99,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000
2020-01-25,99,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000
2020-01-26,99,99.000000,99.000000,99.000000,99.000000,99.000000,99.000000

In [120]:
dframe

,C1,C2,C3,C4,C5,C6,C7
2020-01-20,888,0.261938,555.000000,0.264459,0.441027,777.000000,0.656132
2020-01-21,888,0.512013,0.465007,0.023028,0.540919,777.000000,0.281953
2020-01-22,888,0.088862,0.363900,0.805700,0.142844,777.000000,0.674352
2020-01-23,888,0.188137,0.523349,0.353549,0.027267,0.539622,0.879980
2020-01-24,888,0.326859,0.696649,0.560998,0.078105,0.811292,0.876204
2020-01-25,888,0.492789,0.548214,0.881041,0.340222,0.188474,0.465481
2020-01-26,888,0.336410,0.503548,0.865393,0.408391,0.985424,0.941310

In [121]:
# Display all rows where value of C1 is 99
dframe1[dframe1['C1'] == 99]

            C1    C2    C3    C4    C5    C6    C7
2020-01-22  99  99.0  99.0  99.0  99.0  99.0  99.0
2020-01-24  99  99.0  99.0  99.0  99.0  99.0  99.0
2020-01-25  99  99.0  99.0  99.0  99.0  99.0  99.0
2020-01-26  99  99.0  99.0  99.0  99.0  99.0  99.0

## Dealing with NULL Values

In [122]:
dframe.at[0:8 , 'C7'] = np.NaN
dframe.at[0:2 , 'C6'] = np.NaN
dframe.at[5:6 , 'C5'] = np.NaN
dframe

             C1        C2          C3        C4        C5          C6  C7
2020-01-20  888  0.261938  555.000000  0.264459  0.441027         NaN NaN
2020-01-21  888  0.512013    0.465007  0.023028  0.540919         NaN NaN
2020-01-22  888  0.088862    0.363900  0.805700  0.142844  777.000000 NaN
2020-01-23  888  0.188137    0.523349  0.353549  0.027267    0.539622 NaN
2020-01-24  888  0.326859    0.696649  0.560998  0.078105    0.811292 NaN
2020-01-25  888  0.492789    0.548214  0.881041       NaN    0.188474 NaN
2020-01-26  888  0.336410    0.503548  0.865393  0.408391    0.985424 NaN

In [123]:
# Detect Non-Missing Values
# It will return True for NOT-NULL values and False for NULL values
dframe.notna()

              C1    C2    C3    C4     C5     C6     C7
2020-01-20  True  True  True  True   True  False  False
2020-01-21  True  True  True  True   True  False  False
2020-01-22  True  True  True  True   True   True  False
2020-01-23  True  True  True  True   True   True  False
2020-01-24  True  True  True  True   True   True  False
2020-01-25  True  True  True  True  False   True  False
2020-01-26  True  True  True  True   True   True  False

In [124]:
# Detect Missing or NULL Values
# It will return True for NULL values and False for NOT-NULL values
dframe.isna()

               C1     C2     C3     C4     C5     C6    C7
2020-01-20  False  False  False  False  False   True  True
2020-01-21  False  False  False  False  False   True  True
2020-01-22  False  False  False  False  False  False  True
2020-01-23  False  False  False  False  False  False  True
2020-01-24  False  False  False  False  False  False  True
2020-01-25  False  False  False  False   True  False  True
2020-01-26  False  False  False  False  False  False  True

In [125]:
# Fill all NULL values with 1020
dframe = dframe.fillna(1020)
dframe

,C1,C2,C3,C4,C5,C6,C7
2020-01-20,888,0.261938,555.000000,0.264459,0.441027,1020.000000,1020.0
2020-01-21,888,0.512013,0.465007,0.023028,0.540919,1020.000000,1020.0
2020-01-22,888,0.088862,0.363900,0.805700,0.142844,777.000000,1020.0
2020-01-23,888,0.188137,0.523349,0.353549,0.027267,0.539622,1020.0
2020-01-24,888,0.326859,0.696649,0.560998,0.078105,0.811292,1020.0
2020-01-25,888,0.492789,0.548214,0.881041,1020.000000,0.188474,1020.0
2020-01-26,888,0.336410,0.503548,0.865393,0.408391,0.985424,1020.0

In [126]:
dframe.at[0:5 , 'C7'] = np.NaN
dframe.at[0:2 , 'C6'] = np.NaN
dframe.at[5:6 , 'C5'] = np.NaN
dframe

             C1        C2          C3        C4        C5          C6      C7
2020-01-20  888  0.261938  555.000000  0.264459  0.441027         NaN     NaN
2020-01-21  888  0.512013    0.465007  0.023028  0.540919         NaN     NaN
2020-01-22  888  0.088862    0.363900  0.805700  0.142844  777.000000     NaN
2020-01-23  888  0.188137    0.523349  0.353549  0.027267    0.539622     NaN
2020-01-24  888  0.326859    0.696649  0.560998  0.078105    0.811292     NaN
2020-01-25  888  0.492789    0.548214  0.881041       NaN    0.188474  1020.0
2020-01-26  888  0.336410    0.503548  0.865393  0.408391    0.985424  1020.0

In [127]:
# Replace Null values in Column 'C5' with number 123
# Replace Null values in Column 'C6' with number 789
dframe.fillna(value={'C5' : 123 , 'C6' : 789})

,C1,C2,C3,C4,C5,C6,C7
2020-01-20,888,0.261938,555.000000,0.264459,0.441027,789.000000,NaN
2020-01-21,888,0.512013,0.465007,0.023028,0.540919,789.000000,NaN
2020-01-22,888,0.088862,0.363900,0.805700,0.142844,777.000000,NaN
2020-01-23,888,0.188137,0.523349,0.353549,0.027267,0.539622,NaN
2020-01-24,888,0.326859,0.696649,0.560998,0.078105,0.811292,NaN
2020-01-25,888,0.492789,0.548214,0.881041,123.000000,0.188474,1020.0
2020-01-26,888,0.336410,0.503548,0.865393,0.408391,0.985424,1020.0

In [128]:
#Replace first NULL value in Column C7 with 789
dframe.fillna(value={'C7' : 789} , limit=1)

             C1        C2          C3        C4        C5          C6      C7
2020-01-20  888  0.261938  555.000000  0.264459  0.441027         NaN   789.0
2020-01-21  888  0.512013    0.465007  0.023028  0.540919         NaN     NaN
2020-01-22  888  0.088862    0.363900  0.805700  0.142844  777.000000     NaN
2020-01-23  888  0.188137    0.523349  0.353549  0.027267    0.539622     NaN
2020-01-24  888  0.326859    0.696649  0.560998  0.078105    0.811292     NaN
2020-01-25  888  0.492789    0.548214  0.881041       NaN    0.188474  1020.0
2020-01-26  888  0.336410    0.503548  0.865393  0.408391    0.985424  1020.0

In [129]:
# Drop Rows with NULL values
dframe.dropna()

             C1       C2        C3        C4        C5        C6      C7
2020-01-26  888  0.33641  0.503548  0.865393  0.408391  0.985424  1020.0

In [130]:
# Drop Columns with NULL values
dframe.dropna(axis='columns')

             C1        C2          C3        C4
2020-01-20  888  0.261938  555.000000  0.264459
2020-01-21  888  0.512013    0.465007  0.023028
2020-01-22  888  0.088862    0.363900  0.805700
2020-01-23  888  0.188137    0.523349  0.353549
2020-01-24  888  0.326859    0.696649  0.560998
2020-01-25  888  0.492789    0.548214  0.881041
2020-01-26  888  0.336410    0.503548  0.865393

In [131]:
dframe

             C1        C2          C3        C4        C5          C6      C7
2020-01-20  888  0.261938  555.000000  0.264459  0.441027         NaN     NaN
2020-01-21  888  0.512013    0.465007  0.023028  0.540919         NaN     NaN
2020-01-22  888  0.088862    0.363900  0.805700  0.142844  777.000000     NaN
2020-01-23  888  0.188137    0.523349  0.353549  0.027267    0.539622     NaN
2020-01-24  888  0.326859    0.696649  0.560998  0.078105    0.811292     NaN
2020-01-25  888  0.492789    0.548214  0.881041       NaN    0.188474  1020.0
2020-01-26  888  0.336410    0.503548  0.865393  0.408391    0.985424  1020.0

In [132]:
# Drop Rows with NULL values present in C5 or C6
dframe.dropna(subset=['C5' ,'C6'])

             C1        C2        C3        C4        C5          C6      C7
2020-01-22  888  0.088862  0.363900  0.805700  0.142844  777.000000     NaN
2020-01-23  888  0.188137  0.523349  0.353549  0.027267    0.539622     NaN
2020-01-24  888  0.326859  0.696649  0.560998  0.078105    0.811292     NaN
2020-01-26  888  0.336410  0.503548  0.865393  0.408391    0.985424  1020.0

## Descriptive Statistics

In [ ]:
# Fill NULL values with 55
dframe.fillna(55 , inplace=True)
dframe

NameError: name 'dframe' is not defined

In [141]:
# Mean of all Columns
dframe.mean()

C1    888.000000
C2      0.315287
C3     79.728667
C4      0.536310
C5      8.091222
C6    127.074973
C7    330.714286
dtype: float64

In [142]:
# Max value per column
dframe.max()

C1     888.000000
C2       0.512013
C3     555.000000
C4       0.881041
C5      55.000000
C6     777.000000
C7    1020.000000
dtype: float64

In [143]:
# Min value per column
dframe.min()

C1    888.000000
C2      0.088862
C3      0.363900
C4      0.023028
C5      0.027267
C6      0.188474
C7     55.000000
dtype: float64

In [144]:
# Median 
dframe.median()

C1    888.000000
C2      0.326859
C3      0.523349
C4      0.560998
C5      0.408391
C6      0.985424
C7     55.000000
dtype: float64

In [145]:
dframe.std() #Standard Deviation

C1      0.000000
C2      0.153335
C3    209.574983
C4      0.334435
C5     20.685768
C6    287.733851
C7    470.871785
dtype: float64

In [146]:
dframe.var()  #Variance

C1         0.000000
C2         0.023512
C3     43921.673345
C4         0.111846
C5       427.901005
C6     82790.769050
C7    221720.238095
dtype: float64

In [147]:
#Lower Quartile / First Quartile
dframe.quantile(0.25)

C1    888.000000
C2      0.225038
C3      0.484278
C4      0.309004
C5      0.110475
C6      0.675457
C7     55.000000
Name: 0.25, dtype: float64

In [150]:
#Second Quartile / Median
dframe.quantile(0.50)

C1    888.000000
C2      0.326859
C3      0.523349
C4      0.560998
C5      0.408391
C6      0.985424
C7     55.000000
Name: 0.5, dtype: float64

In [151]:
# Upper Quartile
dframe.quantile(0.75)

C1    888.000000
C2      0.414600
C3      0.622431
C4      0.835547
C5      0.490973
C6     55.000000
C7    537.500000
Name: 0.75, dtype: float64

In [152]:
 #IQR (Interquartile Range)
dframe.quantile(0.75) - dframe.quantile(0.25)

C1      0.000000
C2      0.189562
C3      0.138154
C4      0.526543
C5      0.380499
C6     54.324543
C7    482.500000
dtype: float64

In [ ]:
# SUM of column values
dframe.sum()

NameError: name 'dframe' is not defined

In [154]:
# GENERATES DESCRIPTIVE STATS
dframe.describe()

,C1,C2,C3,C4,C5,C6,C7
count,7.0,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000
mean,888.0,0.315287,79.728667,0.536310,8.091222,127.074973,330.714286
std,0.0,0.153335,209.574983,0.334435,20.685768,287.733851,470.871785
min,888.0,0.088862,0.363900,0.023028,0.027267,0.188474,55.000000
25%,888.0,0.225038,0.484278,0.309004,0.110475,0.675457,55.000000
50%,888.0,0.326859,0.523349,0.560998,0.408391,0.985424,55.000000
75%,888.0,0.414600,0.622431,0.835547,0.490973,55.000000,537.500000
max,888.0,0.512013,555.000000,0.881041,55.000000,777.000000,1020.000000

In [155]:
#Return unbiased skew
# https://www.youtube.com/watch?v=HnMGKsupF8Q
dframe.skew()

C1    0.000000
C2   -0.038755
C3    2.645750
C4   -0.407041
C5    2.645246
C6    2.602476
C7    1.229634
dtype: float64

In [156]:
# Return unbiased kurtosis using Fisher’s definition of kurtosis
# https://www.youtube.com/watch?v=HnMGKsupF8Q
dframe.kurt()

C1    0.000000
C2   -0.850980
C3    6.999995
C4   -1.404482
C5    6.997961
C6    6.821044
C7   -0.840000
dtype: float64

In [ ]:
#Correlation
# https://www.youtube.com/watch?v=qtaqvPAeEJY&list=PLblh5JKOoLUK0FLuzwntyYI10UQFUhsY9&index=10
# https://www.youtube.com/watch?v=xZ_z8KWkhXE&list=PLblh5JKOoLUK0FLuzwntyYI10UQFUhsY9&index=11
dframe.corr()

NameError: name 'dframe' is not defined

In [ ]:
#Covariance
# https://www.youtube.com/watch?v=qtaqvPAeEJY&list=PLblh5JKOoLUK0FLuzwntyYI10UQFUhsY9&index=10
# https://www.youtube.com/watch?v=xZ_z8KWkhXE&list=PLblh5JKOoLUK0FLuzwntyYI10UQFUhsY9&index=11
dframe.cov()

NameError: name 'dframe' is not defined

In [ ]:
import statistics as st
dframe.at[3:5,'C1'] = 22
dframe

NameError: name 'dframe' is not defined

In [160]:
# Average 
st.mean(dframe['C1'])

516.8571428571429

In [161]:
# Hormonic Mean
st.harmonic_mean(dframe['C1'])

49.69186046511628

In [64]:
#Returns average of the two middle numbers when length is EVEN
arr = np.array([1,2,3,4,5,6,7,8])
st.median(arr)

4.5

In [65]:
# low median of the data with EVEN length
st.median_low(arr)

4

In [66]:
# High median of the data with EVEN length
st.median_high(arr)

5

In [165]:
# Mode of Dataset
st.mode(dframe['C7'])

55.0

In [67]:
# Sample Variance
st.variance(dframe['C1'])

NameError: name 'dframe' is not defined

In [167]:
#Population Variance
st.pvariance(dframe['C1'])

183662.69387755104

In [168]:
#Sample  Standard Deviation
st.stdev(dframe['C1'])

462.89647099231905

In [169]:
#Population Standard Deviation
st.pstdev(dframe['C1'])

428.5588569584708

## Apply function on Dataframe

In [170]:
dframe

             C1        C2          C3        C4         C5          C6      C7
2020-01-20  888  0.261938  555.000000  0.264459   0.441027   55.000000    55.0
2020-01-21  888  0.512013    0.465007  0.023028   0.540919   55.000000    55.0
2020-01-22  888  0.088862    0.363900  0.805700   0.142844  777.000000    55.0
2020-01-23   22  0.188137    0.523349  0.353549   0.027267    0.539622    55.0
2020-01-24   22  0.326859    0.696649  0.560998   0.078105    0.811292    55.0
2020-01-25   22  0.492789    0.548214  0.881041  55.000000    0.188474  1020.0
2020-01-26  888  0.336410    0.503548  0.865393   0.408391    0.985424  1020.0

In [171]:
# Finding MAX value in Columns
dframe.apply(max)

C1     888.000000
C2       0.512013
C3     555.000000
C4       0.881041
C5      55.000000
C6     777.000000
C7    1020.000000
dtype: float64

In [172]:
# Finding minimum value in Columns
dframe.apply(min)

C1    22.000000
C2     0.088862
C3     0.363900
C4     0.023028
C5     0.027267
C6     0.188474
C7    55.000000
dtype: float64

In [173]:
#Sum of Column Values
dframe.apply(sum)

C1    3618.000000
C2       2.207008
C3     558.100666
C4       3.754168
C5      56.638553
C6     889.524812
C7    2315.000000
dtype: float64

In [174]:
#Sum of Column Values
dframe.apply(np.sum)

C1    3618.000000
C2       2.207008
C3     558.100666
C4       3.754168
C5      56.638553
C6     889.524812
C7    2315.000000
dtype: float64

In [178]:
# Sum of rows
dframe.apply(np.sum ,axis=1)

2020-01-20    1553.967424
2020-01-21     999.540967
2020-01-22    1721.401306
2020-01-23      78.631924
2020-01-24      79.473902
2020-01-25    1099.110518
2020-01-26    1911.099166
Freq: D, dtype: float64

In [179]:
# Square root of all values in a DataFrame
dframe.applymap(np.sqrt)

,C1,C2,C3,C4,C5,C6,C7
2020-01-20,29.799329,0.511799,23.558438,0.514255,0.664099,7.416198,7.416198
2020-01-21,29.799329,0.715551,0.681914,0.151750,0.735472,7.416198,7.416198
2020-01-22,29.799329,0.298097,0.603241,0.897608,0.377947,27.874720,7.416198
2020-01-23,4.690416,0.433748,0.723428,0.594600,0.165126,0.734590,7.416198
2020-01-24,4.690416,0.571715,0.834655,0.748998,0.279473,0.900717,7.416198
2020-01-25,4.690416,0.701990,0.740414,0.938638,7.416198,0.434136,31.937439
2020-01-26,29.799329,0.580008,0.709611,0.930265,0.639055,0.992685,31.937439

In [180]:
# Square root of all values in a DataFrame
dframe.applymap(math.sqrt)

,C1,C2,C3,C4,C5,C6,C7
2020-01-20,29.799329,0.511799,23.558438,0.514255,0.664099,7.416198,7.416198
2020-01-21,29.799329,0.715551,0.681914,0.151750,0.735472,7.416198,7.416198
2020-01-22,29.799329,0.298097,0.603241,0.897608,0.377947,27.874720,7.416198
2020-01-23,4.690416,0.433748,0.723428,0.594600,0.165126,0.734590,7.416198
2020-01-24,4.690416,0.571715,0.834655,0.748998,0.279473,0.900717,7.416198
2020-01-25,4.690416,0.701990,0.740414,0.938638,7.416198,0.434136,31.937439
2020-01-26,29.799329,0.580008,0.709611,0.930265,0.639055,0.992685,31.937439

In [182]:
dframe.applymap(float)

,C1,C2,C3,C4,C5,C6,C7
2020-01-20,888.0,0.261938,555.000000,0.264459,0.441027,55.000000,55.0
2020-01-21,888.0,0.512013,0.465007,0.023028,0.540919,55.000000,55.0
2020-01-22,888.0,0.088862,0.363900,0.805700,0.142844,777.000000,55.0
2020-01-23,22.0,0.188137,0.523349,0.353549,0.027267,0.539622,55.0
2020-01-24,22.0,0.326859,0.696649,0.560998,0.078105,0.811292,55.0
2020-01-25,22.0,0.492789,0.548214,0.881041,55.000000,0.188474,1020.0
2020-01-26,888.0,0.336410,0.503548,0.865393,0.408391,0.985424,1020.0

In [185]:
# Using Lambda function in Dataframes
dframe.apply(lambda x: np.std(x))

C1    428.558857
C2      0.141961
C3    194.028731
C4      0.309626
C5     19.151300
C6    266.389783
C7    435.942563
dtype: float64

In [192]:
# Using Lambda function in Dataframes
dframe.apply(lambda x: x*x)

,C1,C2,C3,C4,C5,C6,C7
2020-01-20,788544,0.068612,308025.000000,0.069938,0.194505,3025.000000,3025.0
2020-01-21,788544,0.262157,0.216231,0.000530,0.292594,3025.000000,3025.0
2020-01-22,788544,0.007896,0.132423,0.649153,0.020404,603729.000000,3025.0
2020-01-23,484,0.035396,0.273894,0.124997,0.000743,0.291192,3025.0
2020-01-24,484,0.106836,0.485319,0.314718,0.006100,0.658194,3025.0
2020-01-25,484,0.242841,0.300538,0.776233,3025.000000,0.035523,1040400.0
2020-01-26,788544,0.113172,0.253561,0.748906,0.166783,0.971060,1040400.0

# Merge Dataframes

In [193]:
daf1 =  pd.DataFrame ({'id': ['1', '2', '3', '4', '5'], 'Name': ['Anar', 'Vugar', 'Brian', 'John', 'David']})
daf1

  id   Name
0  1   Anar
1  2  Vugar
2  3  Brian
3  4   John
4  5  David

In [194]:
daf2 =  pd.DataFrame ({'id': ['1', '2', '6', '7', '8'], 'Score': [40 , 60 , 80 , 90 , 70]})
daf2

  id  Score
0  1     40
1  2     60
2  6     80
3  7     90
4  8     70

In [195]:
# Inner Join
pd.merge(daf1, daf2, on='id', how='inner')

  id   Name  Score
0  1   Anar     40
1  2  Vugar     60

In [196]:
# Full Outer Join
pd.merge(daf1, daf2, on='id', how='outer')

  id   Name  Score
0  1   Anar   40.0
1  2  Vugar   60.0
2  3  Brian    NaN
3  4   John    NaN
4  5  David    NaN
5  6    NaN   80.0
6  7    NaN   90.0
7  8    NaN   70.0

In [197]:
# Left Outer Join
pd.merge(daf1, daf2, on='id', how='left')

  id   Name  Score
0  1   Anar   40.0
1  2  Vugar   60.0
2  3  Brian    NaN
3  4   John    NaN
4  5  David    NaN

In [198]:
#Right Outer Join
pd.merge(daf1, daf2, on='id', how='right')

  id   Name  Score
0  1   Anar     40
1  2  Vugar     60
2  6    NaN     80
3  7    NaN     90
4  8    NaN     70

# Importing multiple CSV files in DataFrame

In [199]:
data1 = pd.read_csv('C:/Users/User/Desktop/covid_19_clean_complete.csv')
data1.head()

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
0,NaN,Afghanistan,33.93911,67.709953,2020-01-22,0,0,0,0,Eastern Mediterranean
1,NaN,Albania,41.15330,20.168300,2020-01-22,0,0,0,0,Europe
2,NaN,Algeria,28.03390,1.659600,2020-01-22,0,0,0,0,Africa
3,NaN,Andorra,42.50630,1.521800,2020-01-22,0,0,0,0,Europe
4,NaN,Angola,-11.20270,17.873900,2020-01-22,0,0,0,0,Africa

In [200]:
# Append all CSV files 
path =r'C:\Users\DELL\Documents\GitHub\Public\COVID-19\COVID-19\csse_covid_19_data\csse_covid_19_daily_reports'
filenames = glob.g lob(path + "/*.csv")
covid = pd.DataFrame()
for f in filenames:
    df = pd.read_csv(f)
    covid = covid.append(df,ignore_index=True,sort=True)

In [203]:
covid.head()

Empty DataFrame
Columns: []
Index: []

In [204]:
# Top 10 rows of the Dataframe
data1.head(10)

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
0,NaN,Afghanistan,33.93911,67.709953,2020-01-22,0,0,0,0,Eastern Mediterranean
1,NaN,Albania,41.15330,20.168300,2020-01-22,0,0,0,0,Europe
2,NaN,Algeria,28.03390,1.659600,2020-01-22,0,0,0,0,Africa
3,NaN,Andorra,42.50630,1.521800,2020-01-22,0,0,0,0,Europe
4,NaN,Angola,-11.20270,17.873900,2020-01-22,0,0,0,0,Africa
5,NaN,Antigua and Barbuda,17.06080,-61.796400,2020-01-22,0,0,0,0,Americas
6,NaN,Argentina,-38.41610,-63.616700,2020-01-22,0,0,0,0,Americas
7,NaN,Armenia,40.06910,45.038200,2020-01-22,0,0,0,0,Europe
8,Australian Capital Territory,Australia,-35.47350,149.012400,2020-01-22,0,0,0,0,Western Pacific
9,New South Wales,Australia,-33.86880,151.209300,2020-01-22,0,0,0,0,Western Pacific

In [209]:
# Bottom 10 rows of the Dataframe
data1.tail(10)

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
49058,NaN,Malawi,-13.254300,34.301500,2020-07-27,3664,99,1645,1920,Africa
49059,Falkland Islands (Malvinas),United Kingdom,-51.796300,-59.523600,2020-07-27,13,0,13,0,Europe
49060,Saint Pierre and Miquelon,France,46.885200,-56.315900,2020-07-27,4,0,1,3,Europe
49061,NaN,South Sudan,6.877000,31.307000,2020-07-27,2305,46,1175,1084,Africa
49062,NaN,Western Sahara,24.215500,-12.885800,2020-07-27,10,1,8,1,Africa
49063,NaN,Sao Tome and Principe,0.186400,6.613100,2020-07-27,865,14,734,117,Africa
49064,NaN,Yemen,15.552727,48.516388,2020-07-27,1691,483,833,375,Eastern Mediterranean
49065,NaN,Comoros,-11.645500,43.333300,2020-07-27,354,7,328,19,Africa
49066,NaN,Tajikistan,38.861000,71.276100,2020-07-27,7235,60,6028,1147,Europe
49067,NaN,Lesotho,-29.610000,28.233600,2020-07-27,505,12,128,365,Africa

In [210]:
# Unique values in Country column
data1['Country/Region'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia',
       'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
       'Barbados', 'Belarus', 'Belgium', 'Benin', 'Bhutan', 'Bolivia',
       'Bosnia and Herzegovina', 'Brazil', 'Brunei', 'Bulgaria',
       'Burkina Faso', 'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada',
       'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia',
       'Congo (Brazzaville)', 'Congo (Kinshasa)', 'Costa Rica',
       "Cote d'Ivoire", 'Croatia', 'Cuba', 'Cyprus', 'Czechia', 'Denmark',
       'Greenland', 'Djibouti', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon',
       'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Guatemala',
       'Guinea', 'Guyana', 'Haiti', 'Holy See', 'Honduras', 'Hungary',
       'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland',
       'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan',
       'Kenya', 'South Korea', 'Kuwait', 'Kyrgyzstan', 'Latvia',
       'Lebanon', 'Liberia', 'Liechtenstein', 'Lithuania', 'Luxembourg',
       'Madagascar', 'Malaysia', 'Maldives', 'Malta', 'Mauritania',
       'Mauritius', 'Mexico', 'Moldova', 'Monaco', 'Mongolia',
       'Montenegro', 'Morocco', 'Namibia', 'Nepal', 'Netherlands',
       'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North Macedonia',
       'Norway', 'Oman', 'Pakistan', 'Panama', 'Papua New Guinea',
       'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar',
       'Romania', 'Russia', 'Rwanda', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'San Marino', 'Saudi Arabia',
       'Senegal', 'Serbia', 'Seychelles', 'Singapore', 'Slovakia',
       'Slovenia', 'Somalia', 'South Africa', 'Spain', 'Sri Lanka',
       'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Taiwan*',
       'Tanzania', 'Thailand', 'Togo', 'Trinidad and Tobago', 'Tunisia',
       'Turkey', 'Uganda', 'Ukraine', 'United Arab Emirates',
       'United Kingdom', 'Uruguay', 'US', 'Uzbekistan', 'Venezuela',
       'Vietnam', 'Zambia', 'Zimbabwe', 'Dominica', 'Grenada',
       'Mozambique', 'Syria', 'Timor-Leste', 'Belize', 'Laos', 'Libya',
       'West Bank and Gaza', 'Guinea-Bissau', 'Mali',
       'Saint Kitts and Nevis', 'Kosovo', 'Burma', 'Botswana', 'Burundi',
       'Sierra Leone', 'Malawi', 'South Sudan', 'Western Sahara',
       'Sao Tome and Principe', 'Yemen', 'Comoros', 'Tajikistan',
       'Lesotho'], dtype=object)

In [211]:
# Number of Unique values in Country column
data1['Country/Region'].nunique()

187

In [212]:
#Dataframe information
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49068 entries, 0 to 49067
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Province/State  14664 non-null  object
 1   Country/Region  49068 non-null  object
 2   Lat             49068 non-null  float64
 3   Long            49068 non-null  float64
 4   Date            49068 non-null  object
 5   Confirmed       49068 non-null  int64
 6   Deaths          49068 non-null  int64
 7   Recovered       49068 non-null  int64
 8   Active          49068 non-null  int64
 9   WHO Region      49068 non-null  object
dtypes: float64(2), int64(4), object(4)
memory usage: 3.7+ MB

In [213]:
# Reading columns
data1['Country/Region'].head(10)

0            Afghanistan
1                Albania
2                Algeria
3                Andorra
4                 Angola
5    Antigua and Barbuda
6              Argentina
7                Armenia
8              Australia
9              Australia
Name: Country/Region, dtype: object

In [215]:
# Reading columns
df1 = data1[['Country/Region' ,'Province/State','Confirmed' , 'Active']]
df1.head(10)

        Country/Region                Province/State  Confirmed  Active
0          Afghanistan                           NaN          0       0
1              Albania                           NaN          0       0
2              Algeria                           NaN          0       0
3              Andorra                           NaN          0       0
4               Angola                           NaN          0       0
5  Antigua and Barbuda                           NaN          0       0
6            Argentina                           NaN          0       0
7              Armenia                           NaN          0       0
8            Australia  Australian Capital Territory          0       0
9            Australia               New South Wales          0       0

In [216]:
#Read specific rows 
df1.iloc[1:4]

  Country/Region Province/State  Confirmed  Active
1        Albania            NaN          0       0
2        Algeria            NaN          0       0
3        Andorra            NaN          0       0

In [221]:
#Filter data 
df1.loc[df1['Country/Region']== 'Azerbaijan']

      Country/Region Province/State  Confirmed  Active
17        Azerbaijan            NaN          0       0
278       Azerbaijan            NaN          0       0
539       Azerbaijan            NaN          0       0
800       Azerbaijan            NaN          0       0
1061      Azerbaijan            NaN          0       0
...              ...            ...        ...     ...
47780     Azerbaijan            NaN      28980    7615
48041     Azerbaijan            NaN      29312    7365
48302     Azerbaijan            NaN      29633    7143
48563     Azerbaijan            NaN      30050    6949
48824     Azerbaijan            NaN      30446    6781

[188 rows x 4 columns]

In [224]:
#Sort Data Frame
display('Sorted Data Frame', df1.sort_values(['Country/Region'], ascending=True).head(5))

'Sorted Data Frame'

      Country/Region Province/State  Confirmed  Active
0        Afghanistan            NaN          0       0
36801    Afghanistan            NaN      22890   19138
19053    Afghanistan            NaN        299     282
19314    Afghanistan            NaN        349     327
36540    Afghanistan            NaN      22142   18724

In [225]:
#Sort Data Frame
display('Sorted Data Frame', df1.sort_values(['Country/Region'], ascending=False).head(5))

'Sorted Data Frame'

      Country/Region Province/State  Confirmed  Active
40161       Zimbabwe            NaN        525     455
13278       Zimbabwe            NaN          0       0
42249       Zimbabwe            NaN        605     432
48252       Zimbabwe            NaN       2296    1750
10407       Zimbabwe            NaN          0       0

In [226]:
#Sort Data Frame - Ascending on "Country" & descending on "Last update"
display('Sorted Data Frame', df1.sort_values(['Country/Region', 'Active'], ascending=[1,0]).head(5))

'Sorted Data Frame'

      Country/Region Province/State  Confirmed  Active
38106    Afghanistan            NaN      26310   20311
38367    Afghanistan            NaN      26874   20212
37845    Afghanistan            NaN      25527   19885
39672    Afghanistan            NaN      29157   19718
39933    Afghanistan            NaN      29481   19603

In [227]:
#Iterating through the dataset
for index , row in df1.iterrows():
    if (row['Country/Region'] == 'Azerbaijan' ):
        display(row[['Country/Region' ,'Confirmed']])

Country/Region    Azerbaijan
Confirmed                  0
Name: 17, dtype: object

Country/Region    Azerbaijan
Confirmed                  0
Name: 278, dtype: object

Country/Region    Azerbaijan
Confirmed                  0
Name: 539, dtype: object

Country/Region    Azerbaijan
Confirmed                  0
Name: 800, dtype: object

Country/Region    Azerbaijan
Confirmed                  0
Name: 1061, dtype: object

Country/Region    Azerbaijan
Confirmed                  0
Name: 1322, dtype: object

Country/Region    Azerbaijan
Confirmed                  0
Name: 1583, dtype: object

Country/Region    Azerbaijan
Confirmed                  0
Name: 1844, dtype: object

Country/Region    Azerbaijan
Confirmed                  0
Name: 2105, dtype: object

Country/Region    Azerbaijan
Confirmed                  0
Name: 2366, dtype: object

Country/Region    Azerbaijan
Confirmed                  0
Name: 2627, dtype: object

Country/Region    Azerbaijan
Confirmed                  0
Name: 2888, dtype: object

Country/Region    Azerbaijan
Confirmed                  0
Name: 3149, dtype: object

Country/Region    Azerbaijan
Confirmed                  0
Name: 3410, dtype: object

Country/Region    Azerbaijan
Confirmed                  0
Name: 3671, dtype: object

Country/Region    Azerbaijan
Confirmed                  0
Name: 3932, dtype: object

Country/Region    Azerbaijan
Confirmed                  0
Name: 4193, dtype: object

Country/Region    Azerbaijan
Confirmed                  0
Name: 4454, dtype: object

Country/Region    Azerbaijan
Confirmed                  0
Name: 4715, dtype: object

Country/Region    Azerbaijan
Confirmed                  0
Name: 4976, dtype: object

Country/Region    Azerbaijan
Confirmed                  0
Name: 5237, dtype: object

Country/Region    Azerbaijan
Confirmed                  0
Name: 5498, dtype: object

Country/Region    Azerbaijan
Confirmed                  0
Name: 5759, dtype: object

Country/Region    Azerbaijan
Confirmed                  0
Name: 6020, dtype: object

Country/Region    Azerbaijan
Confirmed                  0
Name: 6281, dtype: object

Country/Region    Azerbaijan
Confirmed                  0
Name: 6542, dtype: object

Country/Region    Azerbaijan
Confirmed                  0
Name: 6803, dtype: object

Country/Region    Azerbaijan
Confirmed                  0
Name: 7064, dtype: object

Country/Region    Azerbaijan
Confirmed                  0
Name: 7325, dtype: object

Country/Region    Azerbaijan
Confirmed                  0
Name: 7586, dtype: object

Country/Region    Azerbaijan
Confirmed                  0
Name: 7847, dtype: object

Country/Region    Azerbaijan
Confirmed                  0
Name: 8108, dtype: object

Country/Region    Azerbaijan
Confirmed                  0
Name: 8369, dtype: object

Country/Region    Azerbaijan
Confirmed                  0
Name: 8630, dtype: object

Country/Region    Azerbaijan
Confirmed                  0
Name: 8891, dtype: object

Country/Region    Azerbaijan
Confirmed                  0
Name: 9152, dtype: object

Country/Region    Azerbaijan
Confirmed                  0
Name: 9413, dtype: object

Country/Region    Azerbaijan
Confirmed                  0
Name: 9674, dtype: object

Country/Region    Azerbaijan
Confirmed                  0
Name: 9935, dtype: object

Country/Region    Azerbaijan
Confirmed                  3
Name: 10196, dtype: object

Country/Region    Azerbaijan
Confirmed                  3
Name: 10457, dtype: object

Country/Region    Azerbaijan
Confirmed                  3
Name: 10718, dtype: object

Country/Region    Azerbaijan
Confirmed                  3
Name: 10979, dtype: object

Country/Region    Azerbaijan
Confirmed                  6
Name: 11240, dtype: object

Country/Region    Azerbaijan
Confirmed                  6
Name: 11501, dtype: object

Country/Region    Azerbaijan
Confirmed                  9
Name: 11762, dtype: object

Country/Region    Azerbaijan
Confirmed                  9
Name: 12023, dtype: object

Country/Region    Azerbaijan
Confirmed                  9
Name: 12284, dtype: object

Country/Region    Azerbaijan
Confirmed                 11
Name: 12545, dtype: object

Country/Region    Azerbaijan
Confirmed                 11
Name: 12806, dtype: object

Country/Region    Azerbaijan
Confirmed                 11
Name: 13067, dtype: object

Country/Region    Azerbaijan
Confirmed                 15
Name: 13328, dtype: object

Country/Region    Azerbaijan
Confirmed                 15
Name: 13589, dtype: object

Country/Region    Azerbaijan
Confirmed                 23
Name: 13850, dtype: object

Country/Region    Azerbaijan
Confirmed                 28
Name: 14111, dtype: object

Country/Region    Azerbaijan
Confirmed                 28
Name: 14372, dtype: object

Country/Region    Azerbaijan
Confirmed                 28
Name: 14633, dtype: object

Country/Region    Azerbaijan
Confirmed                 44
Name: 14894, dtype: object

Country/Region    Azerbaijan
Confirmed                 44
Name: 15155, dtype: object

Country/Region    Azerbaijan
Confirmed                 53
Name: 15416, dtype: object

Country/Region    Azerbaijan
Confirmed                 65
Name: 15677, dtype: object

Country/Region    Azerbaijan
Confirmed                 72
Name: 15938, dtype: object

Country/Region    Azerbaijan
Confirmed                 87
Name: 16199, dtype: object

Country/Region    Azerbaijan
Confirmed                 93
Name: 16460, dtype: object

Country/Region    Azerbaijan
Confirmed                122
Name: 16721, dtype: object

Country/Region    Azerbaijan
Confirmed                165
Name: 16982, dtype: object

Country/Region    Azerbaijan
Confirmed                182
Name: 17243, dtype: object

Country/Region    Azerbaijan
Confirmed                209
Name: 17504, dtype: object

Country/Region    Azerbaijan
Confirmed                273
Name: 17765, dtype: object

Country/Region    Azerbaijan
Confirmed                298
Name: 18026, dtype: object

Country/Region    Azerbaijan
Confirmed                359
Name: 18287, dtype: object

Country/Region    Azerbaijan
Confirmed                400
Name: 18548, dtype: object

Country/Region    Azerbaijan
Confirmed                443
Name: 18809, dtype: object

Country/Region    Azerbaijan
Confirmed                521
Name: 19070, dtype: object

Country/Region    Azerbaijan
Confirmed                584
Name: 19331, dtype: object

Country/Region    Azerbaijan
Confirmed                641
Name: 19592, dtype: object

Country/Region    Azerbaijan
Confirmed                717
Name: 19853, dtype: object

Country/Region    Azerbaijan
Confirmed                822
Name: 20114, dtype: object

Country/Region    Azerbaijan
Confirmed                926
Name: 20375, dtype: object

Country/Region    Azerbaijan
Confirmed                991
Name: 20636, dtype: object

Country/Region    Azerbaijan
Confirmed               1058
Name: 20897, dtype: object

Country/Region    Azerbaijan
Confirmed               1098
Name: 21158, dtype: object

Country/Region    Azerbaijan
Confirmed               1148
Name: 21419, dtype: object

Country/Region    Azerbaijan
Confirmed               1197
Name: 21680, dtype: object

Country/Region    Azerbaijan
Confirmed               1253
Name: 21941, dtype: object

Country/Region    Azerbaijan
Confirmed               1283
Name: 22202, dtype: object

Country/Region    Azerbaijan
Confirmed               1340
Name: 22463, dtype: object

Country/Region    Azerbaijan
Confirmed               1373
Name: 22724, dtype: object

Country/Region    Azerbaijan
Confirmed               1398
Name: 22985, dtype: object

Country/Region    Azerbaijan
Confirmed               1436
Name: 23246, dtype: object

Country/Region    Azerbaijan
Confirmed               1480
Name: 23507, dtype: object

Country/Region    Azerbaijan
Confirmed               1518
Name: 23768, dtype: object

Country/Region    Azerbaijan
Confirmed               1548
Name: 24029, dtype: object

Country/Region    Azerbaijan
Confirmed               1592
Name: 24290, dtype: object

Country/Region    Azerbaijan
Confirmed               1617
Name: 24551, dtype: object

Country/Region    Azerbaijan
Confirmed               1645
Name: 24812, dtype: object

Country/Region    Azerbaijan
Confirmed               1678
Name: 25073, dtype: object

Country/Region    Azerbaijan
Confirmed               1717
Name: 25334, dtype: object

Country/Region    Azerbaijan
Confirmed               1766
Name: 25595, dtype: object

Country/Region    Azerbaijan
Confirmed               1804
Name: 25856, dtype: object

Country/Region    Azerbaijan
Confirmed               1854
Name: 26117, dtype: object

Country/Region    Azerbaijan
Confirmed               1894
Name: 26378, dtype: object

Country/Region    Azerbaijan
Confirmed               1932
Name: 26639, dtype: object

Country/Region    Azerbaijan
Confirmed               1984
Name: 26900, dtype: object

Country/Region    Azerbaijan
Confirmed               2060
Name: 27161, dtype: object

Country/Region    Azerbaijan
Confirmed               2127
Name: 27422, dtype: object

Country/Region    Azerbaijan
Confirmed               2204
Name: 27683, dtype: object

Country/Region    Azerbaijan
Confirmed               2279
Name: 27944, dtype: object

Country/Region    Azerbaijan
Confirmed               2422
Name: 28205, dtype: object

Country/Region    Azerbaijan
Confirmed               2519
Name: 28466, dtype: object

Country/Region    Azerbaijan
Confirmed               2589
Name: 28727, dtype: object

Country/Region    Azerbaijan
Confirmed               2693
Name: 28988, dtype: object

Country/Region    Azerbaijan
Confirmed               2758
Name: 29249, dtype: object

Country/Region    Azerbaijan
Confirmed               2879
Name: 29510, dtype: object

Country/Region    Azerbaijan
Confirmed               2980
Name: 29771, dtype: object

Country/Region    Azerbaijan
Confirmed               3138
Name: 30032, dtype: object

Country/Region    Azerbaijan
Confirmed               3274
Name: 30293, dtype: object

Country/Region    Azerbaijan
Confirmed               3387
Name: 30554, dtype: object

Country/Region    Azerbaijan
Confirmed               3518
Name: 30815, dtype: object

Country/Region    Azerbaijan
Confirmed               3631
Name: 31076, dtype: object

Country/Region    Azerbaijan
Confirmed               3749
Name: 31337, dtype: object

Country/Region    Azerbaijan
Confirmed               3855
Name: 31598, dtype: object

Country/Region    Azerbaijan
Confirmed               3982
Name: 31859, dtype: object

Country/Region    Azerbaijan
Confirmed               4122
Name: 32120, dtype: object

Country/Region    Azerbaijan
Confirmed               4271
Name: 32381, dtype: object

Country/Region    Azerbaijan
Confirmed               4403
Name: 32642, dtype: object

Country/Region    Azerbaijan
Confirmed               4568
Name: 32903, dtype: object

Country/Region    Azerbaijan
Confirmed               4759
Name: 33164, dtype: object

Country/Region    Azerbaijan
Confirmed               4989
Name: 33425, dtype: object

Country/Region    Azerbaijan
Confirmed               5246
Name: 33686, dtype: object

Country/Region    Azerbaijan
Confirmed               5494
Name: 33947, dtype: object

Country/Region    Azerbaijan
Confirmed               5662
Name: 34208, dtype: object

Country/Region    Azerbaijan
Confirmed               5935
Name: 34469, dtype: object

Country/Region    Azerbaijan
Confirmed               6260
Name: 34730, dtype: object

Country/Region    Azerbaijan
Confirmed               6522
Name: 34991, dtype: object

Country/Region    Azerbaijan
Confirmed               6860
Name: 35252, dtype: object

Country/Region    Azerbaijan
Confirmed               7239
Name: 35513, dtype: object

Country/Region    Azerbaijan
Confirmed               7553
Name: 35774, dtype: object

Country/Region    Azerbaijan
Confirmed               7876
Name: 36035, dtype: object

Country/Region    Azerbaijan
Confirmed               8191
Name: 36296, dtype: object

Country/Region    Azerbaijan
Confirmed               8530
Name: 36557, dtype: object

Country/Region    Azerbaijan
Confirmed               8882
Name: 36818, dtype: object

Country/Region    Azerbaijan
Confirmed               9218
Name: 37079, dtype: object

Country/Region    Azerbaijan
Confirmed               9570
Name: 37340, dtype: object

Country/Region    Azerbaijan
Confirmed               9957
Name: 37601, dtype: object

Country/Region    Azerbaijan
Confirmed              10324
Name: 37862, dtype: object

Country/Region    Azerbaijan
Confirmed              10662
Name: 38123, dtype: object

Country/Region    Azerbaijan
Confirmed              10991
Name: 38384, dtype: object

Country/Region    Azerbaijan
Confirmed              11329
Name: 38645, dtype: object

Country/Region    Azerbaijan
Confirmed              11767
Name: 38906, dtype: object

Country/Region    Azerbaijan
Confirmed              12238
Name: 39167, dtype: object

Country/Region    Azerbaijan
Confirmed              12729
Name: 39428, dtype: object

Country/Region    Azerbaijan
Confirmed              13207
Name: 39689, dtype: object

Country/Region    Azerbaijan
Confirmed              13715
Name: 39950, dtype: object

Country/Region    Azerbaijan
Confirmed              14305
Name: 40211, dtype: object

Country/Region    Azerbaijan
Confirmed              14852
Name: 40472, dtype: object

Country/Region    Azerbaijan
Confirmed              15369
Name: 40733, dtype: object

Country/Region    Azerbaijan
Confirmed              15890
Name: 40994, dtype: object

Country/Region    Azerbaijan
Confirmed              16424
Name: 41255, dtype: object

Country/Region    Azerbaijan
Confirmed              16968
Name: 41516, dtype: object

Country/Region    Azerbaijan
Confirmed              17524
Name: 41777, dtype: object

Country/Region    Azerbaijan
Confirmed              18112
Name: 42038, dtype: object

Country/Region    Azerbaijan
Confirmed              18684
Name: 42299, dtype: object

Country/Region    Azerbaijan
Confirmed              19267
Name: 42560, dtype: object

Country/Region    Azerbaijan
Confirmed              19801
Name: 42821, dtype: object

Country/Region    Azerbaijan
Confirmed              20324
Name: 43082, dtype: object

Country/Region    Azerbaijan
Confirmed              20837
Name: 43343, dtype: object

Country/Region    Azerbaijan
Confirmed              21374
Name: 43604, dtype: object

Country/Region    Azerbaijan
Confirmed              21916
Name: 43865, dtype: object

Country/Region    Azerbaijan
Confirmed              22464
Name: 44126, dtype: object

Country/Region    Azerbaijan
Confirmed              22990
Name: 44387, dtype: object

Country/Region    Azerbaijan
Confirmed              23521
Name: 44648, dtype: object

Country/Region    Azerbaijan
Confirmed              24041
Name: 44909, dtype: object

Country/Region    Azerbaijan
Confirmed              24570
Name: 45170, dtype: object

Country/Region    Azerbaijan
Confirmed              25113
Name: 45431, dtype: object

Country/Region    Azerbaijan
Confirmed              25672
Name: 45692, dtype: object

Country/Region    Azerbaijan
Confirmed              26165
Name: 45953, dtype: object

Country/Region    Azerbaijan
Confirmed              26636
Name: 46214, dtype: object

Country/Region    Azerbaijan
Confirmed              27133
Name: 46475, dtype: object

Country/Region    Azerbaijan
Confirmed              27521
Name: 46736, dtype: object

Country/Region    Azerbaijan
Confirmed              27890
Name: 46997, dtype: object

Country/Region    Azerbaijan
Confirmed              28242
Name: 47258, dtype: object

Country/Region    Azerbaijan
Confirmed              28633
Name: 47519, dtype: object

Country/Region    Azerbaijan
Confirmed              28980
Name: 47780, dtype: object

Country/Region    Azerbaijan
Confirmed              29312
Name: 48041, dtype: object

Country/Region    Azerbaijan
Confirmed              29633
Name: 48302, dtype: object

Country/Region    Azerbaijan
Confirmed              30050
Name: 48563, dtype: object

Country/Region    Azerbaijan
Confirmed              30446
Name: 48824, dtype: object

In [231]:
#Unique Values
data1['Country/Region'].drop_duplicates(keep='first').head(10)

0             Afghanistan
1                 Albania
2                 Algeria
3                 Andorra
4                  Angola
5     Antigua and Barbuda
6               Argentina
7                 Armenia
8               Australia
16                Austria
Name: Country/Region, dtype: object

In [232]:
# Countries impacted with Coronavirus
countries = data1['Country/Region'].unique()
type(countries) , countries

(numpy.ndarray,
 array(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
        'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia',
        'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
        'Barbados', 'Belarus', 'Belgium', 'Benin', 'Bhutan', 'Bolivia',
        'Bosnia and Herzegovina', 'Brazil', 'Brunei', 'Bulgaria',
        'Burkina Faso', 'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada',
        'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia',
        'Congo (Brazzaville)', 'Congo (Kinshasa)', 'Costa Rica',
        "Cote d'Ivoire", 'Croatia', 'Cuba', 'Cyprus', 'Czechia', 'Denmark',
        'Greenland', 'Djibouti', 'Dominican Republic', 'Ecuador', 'Egypt',
        'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
        'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon',
        'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Guatemala',
        'Guinea', 'Guyana', 'Haiti', 'Holy See', 'Honduras', 'Hungary',
        'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland',
        'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan',
        'Kenya', 'South Korea', 'Kuwait', 'Kyrgyzstan', 'Latvia',
        'Lebanon', 'Liberia', 'Liechtenstein', 'Lithuania', 'Luxembourg',
        'Madagascar', 'Malaysia', 'Maldives', 'Malta', 'Mauritania',
        'Mauritius', 'Mexico', 'Moldova', 'Monaco', 'Mongolia',
        'Montenegro', 'Morocco', 'Namibia', 'Nepal', 'Netherlands',
        'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North Macedonia',
        'Norway', 'Oman', 'Pakistan', 'Panama', 'Papua New Guinea',
        'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar',
        'Romania', 'Russia', 'Rwanda', 'Saint Lucia',
        'Saint Vincent and the Grenadines', 'San Marino', 'Saudi Arabia',
        'Senegal', 'Serbia', 'Seychelles', 'Singapore', 'Slovakia',
        'Slovenia', 'Somalia', 'South Africa', 'Spain', 'Sri Lanka',
        'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Taiwan*',
        'Tanzania', 'Thailand', 'Togo', 'Trinidad and Tobago', 'Tunisia',
        'Turkey', 'Uganda', 'Ukraine', 'United Arab Emirates',
        'United Kingdom', 'Uruguay', 'US', 'Uzbekistan', 'Venezuela',
        'Vietnam', 'Zambia', 'Zimbabwe', 'Dominica', 'Grenada',
        'Mozambique', 'Syria', 'Timor-Leste', 'Belize', 'Laos', 'Libya',
        'West Bank and Gaza', 'Guinea-Bissau', 'Mali',
        'Saint Kitts and Nevis', 'Kosovo', 'Burma', 'Botswana', 'Burundi',
        'Sierra Leone', 'Malawi', 'South Sudan', 'Western Sahara',
        'Sao Tome and Principe', 'Yemen', 'Comoros', 'Tajikistan',
        'Lesotho'], dtype=object))

In [233]:
df2 = pd.read_csv('C:/Users/User/Desktop/Pokemon.csv')
df2.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [234]:
# Sum of Columns 
df2['Total'] = df2['HP'] + df2['Attack']
df2.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,94,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,122,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,162,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,180,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,91,39,52,43,60,50,65,1,False

In [235]:
# Sum of Columns 
df2['Total'] = df2.iloc[:,4:10].sum(axis=1)
df2.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,367,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,467,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,607,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,725,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,335,39,52,43,60,50,65,1,False

In [236]:
#Shifting "Total" column

cols = list(df2.columns)

df2 = df2[cols[0:10] + [cols[-1]] + cols[10:12]]
df2.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Legendary,Speed,Generation
0,1,Bulbasaur,Grass,Poison,367,45,49,49,65,65,False,45,1
1,2,Ivysaur,Grass,Poison,467,60,62,63,80,80,False,60,1
2,3,Venusaur,Grass,Poison,607,80,82,83,100,100,False,80,1
3,3,VenusaurMega Venusaur,Grass,Poison,725,80,100,123,122,120,False,80,1
4,4,Charmander,Fire,NaN,335,39,52,43,60,50,False,65,1

In [237]:
#Shifting "Legendary" column -  Index location -1 or 12

cols = list(df2.columns)

df2 = df2[cols[0:10] + [cols[-1]] + cols[10:12]]
df2.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Generation,Legendary,Speed
0,1,Bulbasaur,Grass,Poison,367,45,49,49,65,65,1,False,45
1,2,Ivysaur,Grass,Poison,467,60,62,63,80,80,1,False,60
2,3,Venusaur,Grass,Poison,607,80,82,83,100,100,1,False,80
3,3,VenusaurMega Venusaur,Grass,Poison,725,80,100,123,122,120,1,False,80
4,4,Charmander,Fire,NaN,335,39,52,43,60,50,1,False,65

In [238]:
#Shifting "Generation" column - Index location -1 or 12

cols = list(df2.columns)

df2 = df2[cols[0:10] + [cols[12]] + cols[10:12]]
df2.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,367,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,467,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,607,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,725,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,335,39,52,43,60,50,65,1,False

In [ ]:
#Save to CSV file

df2.to_csv('poke_updated.csv')

In [ ]:
#Save to CSV file without index column

df2.to_csv('poke_updated1.csv', index=False)

In [239]:
df2.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,367,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,467,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,607,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,725,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,335,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,447,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,596,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,742,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,716,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,363,44,48,65,50,64,43,1,False

In [240]:
# Save Dataframe as text file
df2.to_csv('poke.txt' , sep='\t' , index=False)

In [241]:
# Save Dataframe as xlsx file
df2.to_excel('poke.xlsx')

In [242]:
# Save Dataframe as xlsx file without row names
df2.to_excel('poke.xlsx', index=0)

In [243]:
#Filtering using loc

df2.loc[df2['Type 2'] == 'Dragon']

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
7,6,CharizardMega Charizard X,Fire,Dragon,742,78,130,111,130,85,100,1,False
196,181,AmpharosMega Ampharos,Electric,Dragon,750,90,95,105,165,110,45,2,False
249,230,Kingdra,Water,Dragon,625,75,95,95,95,95,85,2,False
275,254,SceptileMega Sceptile,Grass,Dragon,665,70,110,75,145,85,145,3,False
360,329,Vibrava,Ground,Dragon,390,50,70,50,50,50,70,3,False
361,330,Flygon,Ground,Dragon,600,80,100,80,80,80,100,3,False
540,483,Dialga,Steel,Dragon,810,100,120,120,150,100,90,4,True
541,484,Palkia,Water,Dragon,790,90,120,100,150,120,100,4,True
544,487,GiratinaAltered Forme,Ghost,Dragon,840,150,100,120,100,120,90,4,True
545,487,GiratinaOrigin Forme,Ghost,Dragon,860,150,120,100,120,100,90,4,True
694,633,Deino,Dark,Dragon,379,52,65,50,45,50,38,5,False
695,634,Zweilous,Dark,Dragon,519,72,85,70,65,70,58,5,False
696,635,Hydreigon,Dark,Dragon,699,92,105,90,125,90,98,5,False
761,691,Dragalge,Poison,Dragon,590,65,75,90,97,123,44,6,False
766,696,Tyrunt,Rock,Dragon,461,58,89,77,45,45,48,6,False
767,697,Tyrantrum,Rock,Dragon,653,82,121,119,69,59,71,6,False
790,714,Noibat,Flying,Dragon,260,40,30,35,45,40,55,6,False
791,715,Noivern,Flying,Dragon,567,85,70,80,97,80,123,6,False

In [244]:
#Filtering using loc
df3 = df2.loc[(df2['Type 2'] == 'Dragon') & (df2['Type 1'] == 'Dark')]
df3

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
694,633,Deino,Dark,Dragon,379,52,65,50,45,50,38,5,False
695,634,Zweilous,Dark,Dragon,519,72,85,70,65,70,58,5,False
696,635,Hydreigon,Dark,Dragon,699,92,105,90,125,90,98,5,False

In [245]:
#Reset index for Dataframe df3 keeping old index column

df4 = df3.reset_index()
df4

,index,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,694,633,Deino,Dark,Dragon,379,52,65,50,45,50,38,5,False
1,695,634,Zweilous,Dark,Dragon,519,72,85,70,65,70,58,5,False
2,696,635,Hydreigon,Dark,Dragon,699,92,105,90,125,90,98,5,False

In [246]:
#Reset index for Dataframe df3 removing old index column

df3.reset_index(drop=True , inplace=True)
df3

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,633,Deino,Dark,Dragon,379,52,65,50,45,50,38,5,False
1,634,Zweilous,Dark,Dragon,519,72,85,70,65,70,58,5,False
2,635,Hydreigon,Dark,Dragon,699,92,105,90,125,90,98,5,False

In [247]:
df2.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,367,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,467,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,607,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,725,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,335,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,447,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,596,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,742,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,716,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,363,44,48,65,50,64,43,1,False

# LIKE OPERATION IN PANDAS

In [248]:
df2.Name.str.contains("rill").head(10)

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
Name: Name, dtype: bool

In [249]:
# Display all rows containing Name "rill"
df2.loc[df2.Name.str.contains("rill")]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
18,15,Beedrill,Bug,Poison,475,65,90,40,45,80,75,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,565,65,150,40,15,80,145,1,False
198,183,Marill,Water,Fairy,300,70,20,50,20,50,40,2,False
199,184,Azumarill,Water,Fairy,520,100,50,80,60,80,50,2,False
322,298,Azurill,Normal,Fairy,240,50,20,40,20,40,20,3,False
589,530,Excadrill,Ground,Steel,665,110,135,60,50,65,88,5,False
653,592,Frillish,Water,Ghost,390,55,40,50,65,85,40,5,False

In [250]:
# Exclude all rows containing "rill"
df2.loc[~df2.Name.str.contains("rill")].head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,367,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,467,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,607,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,725,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,335,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,447,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,596,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,742,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,716,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,363,44,48,65,50,64,43,1,False

In [254]:
#Display all rows with Type-1 as "Grass" and Type-2 as "Poison"

df2.loc[df2['Type 1'].str.contains("Grass") & df2['Type 2'].str.contains("Poison")]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,367,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,467,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,607,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,725,80,100,123,122,120,80,1,False
48,43,Oddish,Grass,Poison,385,45,50,55,75,65,30,1,False
49,44,Gloom,Grass,Poison,480,60,65,70,85,75,40,1,False
50,45,Vileplume,Grass,Poison,595,75,80,85,110,90,50,1,False
75,69,Bellsprout,Grass,Poison,385,50,75,35,70,30,40,1,False
76,70,Weepinbell,Grass,Poison,490,65,90,50,85,45,55,1,False
77,71,Victreebel,Grass,Poison,605,80,105,65,100,70,70,1,False
344,315,Roselia,Grass,Poison,445,50,60,45,100,80,65,3,False
451,406,Budew,Grass,Poison,295,40,30,35,50,70,55,4,False
452,407,Roserade,Grass,Poison,555,60,70,65,125,105,90,4,False
651,590,Foongus,Grass,Poison,403,69,55,45,55,55,15,5,False
652,591,Amoonguss,Grass,Poison,633,114,85,70,85,80,30,5,False

In [257]:
df2.loc[df2['Type 1'].str.contains('Grass|Water',regex = True)].head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,367,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,467,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,607,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,725,80,100,123,122,120,80,1,False
9,7,Squirtle,Water,NaN,363,44,48,65,50,64,43,1,False

In [258]:
# Due to Case-sensitive it will not return any data

df2.loc[df2['Type 1'].str.contains('grass|water',regex = True)].head(10)

Empty DataFrame
Columns: [#, Name, Type 1, Type 2, Total, HP, Attack, Defense, Sp. Atk, Sp. Def, Speed, Generation, Legendary]
Index: []

In [259]:
# To ignore case we can use "case = False"

df2.loc[df2['Type 1'].str.contains('grass|water', case = False ,regex = True)].head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,367,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,467,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,607,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,725,80,100,123,122,120,80,1,False
9,7,Squirtle,Water,NaN,363,44,48,65,50,64,43,1,False
10,8,Wartortle,Water,NaN,469,59,63,80,65,80,58,1,False
11,9,Blastoise,Water,NaN,614,79,83,100,85,105,78,1,False
12,9,BlastoiseMega Blastoise,Water,NaN,734,79,103,120,135,115,78,1,False
48,43,Oddish,Grass,Poison,385,45,50,55,75,65,30,1,False
49,44,Gloom,Grass,Poison,480,60,65,70,85,75,40,1,False

In [260]:
# To ignore case we can use "Flags = re.I"

df2.loc[df2['Type 1'].str.contains('grass|water',flags = re.I ,regex = True)].head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,367,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,467,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,607,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,725,80,100,123,122,120,80,1,False
9,7,Squirtle,Water,NaN,363,44,48,65,50,64,43,1,False
10,8,Wartortle,Water,NaN,469,59,63,80,65,80,58,1,False
11,9,Blastoise,Water,NaN,614,79,83,100,85,105,78,1,False
12,9,BlastoiseMega Blastoise,Water,NaN,734,79,103,120,135,115,78,1,False
48,43,Oddish,Grass,Poison,385,45,50,55,75,65,30,1,False
49,44,Gloom,Grass,Poison,480,60,65,70,85,75,40,1,False

# Regex in Pandas dataframe

In [261]:
#Get all rows with name starting with "wa"

df2.loc[df2.Name.str.contains('^Wa',flags = re.I ,regex = True)].head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
10,8,Wartortle,Water,NaN,469,59,63,80,65,80,58,1,False
350,320,Wailmer,Water,NaN,540,130,70,35,70,35,60,3,False
351,321,Wailord,Water,NaN,700,170,90,45,90,45,60,3,False
400,365,Walrein,Ice,Water,655,110,80,90,95,90,65,3,False
564,505,Watchog,Normal,NaN,488,60,85,69,60,69,77,5,False

In [262]:
#Get all rows with name starting with "wa" followed by any letter between a-l

df2.loc[df2.Name.str.contains('^Wa[a-l]+',flags = re.I ,regex = True)].head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
350,320,Wailmer,Water,NaN,540,130,70,35,70,35,60,3,False
351,321,Wailord,Water,NaN,700,170,90,45,90,45,60,3,False
400,365,Walrein,Ice,Water,655,110,80,90,95,90,65,3,False

In [263]:
#Get all rows with name starting with x , y, z

df2.loc[df2.Name.str.contains('^[x-z]',flags = re.I ,regex = True)]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
46,41,Zubat,Poison,Flying,275,40,45,35,30,40,55,1,False
157,145,Zapdos,Electric,Flying,660,90,90,85,125,90,100,1,True
192,178,Xatu,Psychic,Flying,515,65,75,70,95,70,95,2,False
208,193,Yanma,Bug,Flying,425,65,65,45,75,45,95,2,False
286,263,Zigzagoon,Normal,NaN,248,38,30,41,30,41,60,3,False
367,335,Zangoose,Normal,NaN,556,73,115,60,60,60,90,3,False
520,469,Yanmega,Bug,Flying,582,86,76,86,116,56,95,4,False
582,523,Zebstrika,Electric,NaN,556,75,100,63,80,63,116,5,False
623,562,Yamask,Ghost,NaN,341,38,30,85,55,65,30,5,False
631,570,Zorua,Dark,NaN,370,40,65,40,80,40,65,5,False
632,571,Zoroark,Dark,NaN,570,60,105,60,120,60,105,5,False
695,634,Zweilous,Dark,Dragon,519,72,85,70,65,70,58,5,False
707,644,Zekrom,Dragon,Electric,840,100,150,120,120,100,90,5,True
792,716,Xerneas,Fairy,NaN,838,126,131,95,131,98,99,6,True
793,717,Yveltal,Dark,Flying,838,126,131,95,131,98,99,6,True
794,718,Zygarde50% Forme,Dragon,Ground,713,108,100,121,81,95,95,6,True

In [264]:
# Extracting first 3 characters from "Name" column
df2['Name2'] = df2.Name.str.extract(r'(^\w{3})')

In [265]:
df2.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Name2
0,1,Bulbasaur,Grass,Poison,367,45,49,49,65,65,45,1,False,Bul
1,2,Ivysaur,Grass,Poison,467,60,62,63,80,80,60,1,False,Ivy
2,3,Venusaur,Grass,Poison,607,80,82,83,100,100,80,1,False,Ven
3,3,VenusaurMega Venusaur,Grass,Poison,725,80,100,123,122,120,80,1,False,Ven
4,4,Charmander,Fire,NaN,335,39,52,43,60,50,65,1,False,Cha

In [266]:
# Return all rows with "Name" starting with character 'B or b' 
df2.loc[df2.Name.str.match(r'(^[B|b].*)')].head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Name2
0,1,Bulbasaur,Grass,Poison,367,45,49,49,65,65,45,1,False,Bul
11,9,Blastoise,Water,NaN,614,79,83,100,85,105,78,1,False,Bla
12,9,BlastoiseMega Blastoise,Water,NaN,734,79,103,120,135,115,78,1,False,Bla
15,12,Butterfree,Bug,Flying,430,60,45,50,90,80,70,1,False,But
18,15,Beedrill,Bug,Poison,475,65,90,40,45,80,75,1,False,Bee

# Replace values in dataframe

In [267]:
df2.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Name2
0,1,Bulbasaur,Grass,Poison,367,45,49,49,65,65,45,1,False,Bul
1,2,Ivysaur,Grass,Poison,467,60,62,63,80,80,60,1,False,Ivy
2,3,Venusaur,Grass,Poison,607,80,82,83,100,100,80,1,False,Ven
3,3,VenusaurMega Venusaur,Grass,Poison,725,80,100,123,122,120,80,1,False,Ven
4,4,Charmander,Fire,NaN,335,39,52,43,60,50,65,1,False,Cha
5,5,Charmeleon,Fire,NaN,447,58,64,58,80,65,80,1,False,Cha
6,6,Charizard,Fire,Flying,596,78,84,78,109,85,100,1,False,Cha
7,6,CharizardMega Charizard X,Fire,Dragon,742,78,130,111,130,85,100,1,False,Cha
8,6,CharizardMega Charizard Y,Fire,Flying,716,78,104,78,159,115,100,1,False,Cha
9,7,Squirtle,Water,NaN,363,44,48,65,50,64,43,1,False,Squ

In [268]:
df2['Type 1'] = df2['Type 1'].replace({"Grass" : "Meadow" , "Fire" :"Blaze"})

In [269]:
df2.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Name2
0,1,Bulbasaur,Meadow,Poison,367,45,49,49,65,65,45,1,False,Bul
1,2,Ivysaur,Meadow,Poison,467,60,62,63,80,80,60,1,False,Ivy
2,3,Venusaur,Meadow,Poison,607,80,82,83,100,100,80,1,False,Ven
3,3,VenusaurMega Venusaur,Meadow,Poison,725,80,100,123,122,120,80,1,False,Ven
4,4,Charmander,Blaze,NaN,335,39,52,43,60,50,65,1,False,Cha
5,5,Charmeleon,Blaze,NaN,447,58,64,58,80,65,80,1,False,Cha
6,6,Charizard,Blaze,Flying,596,78,84,78,109,85,100,1,False,Cha
7,6,CharizardMega Charizard X,Blaze,Dragon,742,78,130,111,130,85,100,1,False,Cha
8,6,CharizardMega Charizard Y,Blaze,Flying,716,78,104,78,159,115,100,1,False,Cha
9,7,Squirtle,Water,NaN,363,44,48,65,50,64,43,1,False,Squ

In [270]:
df2['Type 2'] = df2['Type 2'].replace({"Poison" : "Venom"})

In [271]:
df2.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Name2
0,1,Bulbasaur,Meadow,Venom,367,45,49,49,65,65,45,1,False,Bul
1,2,Ivysaur,Meadow,Venom,467,60,62,63,80,80,60,1,False,Ivy
2,3,Venusaur,Meadow,Venom,607,80,82,83,100,100,80,1,False,Ven
3,3,VenusaurMega Venusaur,Meadow,Venom,725,80,100,123,122,120,80,1,False,Ven
4,4,Charmander,Blaze,NaN,335,39,52,43,60,50,65,1,False,Cha

In [272]:
df2['Type 2'] = df2['Type 2'].replace(['Venom' , 'Dragon'] , 'DANGER')

In [273]:
df2.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Name2
0,1,Bulbasaur,Meadow,DANGER,367,45,49,49,65,65,45,1,False,Bul
1,2,Ivysaur,Meadow,DANGER,467,60,62,63,80,80,60,1,False,Ivy
2,3,Venusaur,Meadow,DANGER,607,80,82,83,100,100,80,1,False,Ven
3,3,VenusaurMega Venusaur,Meadow,DANGER,725,80,100,123,122,120,80,1,False,Ven
4,4,Charmander,Blaze,NaN,335,39,52,43,60,50,65,1,False,Cha
5,5,Charmeleon,Blaze,NaN,447,58,64,58,80,65,80,1,False,Cha
6,6,Charizard,Blaze,Flying,596,78,84,78,109,85,100,1,False,Cha
7,6,CharizardMega Charizard X,Blaze,DANGER,742,78,130,111,130,85,100,1,False,Cha
8,6,CharizardMega Charizard Y,Blaze,Flying,716,78,104,78,159,115,100,1,False,Cha
9,7,Squirtle,Water,NaN,363,44,48,65,50,64,43,1,False,Squ

In [274]:
df2.loc[df2['Type 2'] == 'DANGER' , 'Name2'] = np.NaN

In [275]:
df2.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Name2
0,1,Bulbasaur,Meadow,DANGER,367,45,49,49,65,65,45,1,False,NaN
1,2,Ivysaur,Meadow,DANGER,467,60,62,63,80,80,60,1,False,NaN
2,3,Venusaur,Meadow,DANGER,607,80,82,83,100,100,80,1,False,NaN
3,3,VenusaurMega Venusaur,Meadow,DANGER,725,80,100,123,122,120,80,1,False,NaN
4,4,Charmander,Blaze,NaN,335,39,52,43,60,50,65,1,False,Cha
5,5,Charmeleon,Blaze,NaN,447,58,64,58,80,65,80,1,False,Cha
6,6,Charizard,Blaze,Flying,596,78,84,78,109,85,100,1,False,Cha
7,6,CharizardMega Charizard X,Blaze,DANGER,742,78,130,111,130,85,100,1,False,NaN
8,6,CharizardMega Charizard Y,Blaze,Flying,716,78,104,78,159,115,100,1,False,Cha
9,7,Squirtle,Water,NaN,363,44,48,65,50,64,43,1,False,Squ

In [276]:
df2.loc[df2['Total'] > 400 , ['Name2' , 'Legendary']] = 'ALERT'
df2.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Name2
0,1,Bulbasaur,Meadow,DANGER,367,45,49,49,65,65,45,1,False,NaN
1,2,Ivysaur,Meadow,DANGER,467,60,62,63,80,80,60,1,ALERT,ALERT
2,3,Venusaur,Meadow,DANGER,607,80,82,83,100,100,80,1,ALERT,ALERT
3,3,VenusaurMega Venusaur,Meadow,DANGER,725,80,100,123,122,120,80,1,ALERT,ALERT
4,4,Charmander,Blaze,NaN,335,39,52,43,60,50,65,1,False,Cha
5,5,Charmeleon,Blaze,NaN,447,58,64,58,80,65,80,1,ALERT,ALERT
6,6,Charizard,Blaze,Flying,596,78,84,78,109,85,100,1,ALERT,ALERT
7,6,CharizardMega Charizard X,Blaze,DANGER,742,78,130,111,130,85,100,1,ALERT,ALERT
8,6,CharizardMega Charizard Y,Blaze,Flying,716,78,104,78,159,115,100,1,ALERT,ALERT
9,7,Squirtle,Water,NaN,363,44,48,65,50,64,43,1,False,Squ

In [277]:
df2.loc[df2['Total'] > 400 , ['Legendary' , 'Name2']] = ['ALERT-1' , 'ALERT-2'] 
df2.head(10)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Name2
0,1,Bulbasaur,Meadow,DANGER,367,45,49,49,65,65,45,1,False,NaN
1,2,Ivysaur,Meadow,DANGER,467,60,62,63,80,80,60,1,ALERT-1,ALERT-2
2,3,Venusaur,Meadow,DANGER,607,80,82,83,100,100,80,1,ALERT-1,ALERT-2
3,3,VenusaurMega Venusaur,Meadow,DANGER,725,80,100,123,122,120,80,1,ALERT-1,ALERT-2
4,4,Charmander,Blaze,NaN,335,39,52,43,60,50,65,1,False,Cha
5,5,Charmeleon,Blaze,NaN,447,58,64,58,80,65,80,1,ALERT-1,ALERT-2
6,6,Charizard,Blaze,Flying,596,78,84,78,109,85,100,1,ALERT-1,ALERT-2
7,6,CharizardMega Charizard X,Blaze,DANGER,742,78,130,111,130,85,100,1,ALERT-1,ALERT-2
8,6,CharizardMega Charizard Y,Blaze,Flying,716,78,104,78,159,115,100,1,ALERT-1,ALERT-2
9,7,Squirtle,Water,NaN,363,44,48,65,50,64,43,1,False,Squ

# Group By

In [279]:
df = pd.read_csv('C:/Users/User/Desktop/Pokemon.csv')
df.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [288]:
df.groupby(['Type 1']).nunique()

,#,Name,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,,,,
Bug,63,69,11,45,22,41,32,31,31,33,6,1
Dark,28,31,8,25,20,17,21,22,18,23,5,2
Dragon,24,32,7,14,19,21,15,18,18,19,5,2
Electric,36,44,10,33,18,22,24,24,24,25,6,2
Fairy,17,17,1,16,15,14,15,15,14,16,4,2
Fighting,25,27,4,18,19,18,16,16,15,21,6,1
Fire,47,52,9,39,27,36,29,31,26,29,6,2
Flying,3,4,1,3,3,4,3,4,3,4,2,2
Ghost,23,32,6,23,20,20,22,21,20,25,6,2
Grass,66,70,10,50,25,37,30,40,29,38,6,2
Ground,30,32,9,28,20,25,21,18,16,23,5,2
Ice,23,24,5,17,13,16,14,17,16,16,6,2
Normal,93,98,7,74,42,39,41,39,43,44,6,2
Poison,28,28,7,23,21,23,24,16,20,20,6,1
Psychic,47,57,7,35,28,30,27,32,25,34,6,2
Rock,41,44,12,23,23,31,27,28,26,27,6,2
Steel,22,27,8,21,13,18,19,16,19,14,5,2
Water,105,112,14,63,41,52,42,50,40,43,6,2

In [291]:
df.groupby(['Type 1']).std().head(10)

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,,
Bug,210.445160,117.875223,16.328914,37.040904,33.617609,26.697055,32.126395,33.227599,1.598433,0.000000
Dark,176.022072,109.126217,21.078297,25.774247,25.121982,33.200952,24.799020,27.768203,1.353609,0.249731
Dragon,170.190169,146.267538,23.795415,33.742622,24.102938,42.257360,29.884843,23.239961,1.431219,0.491869
Electric,202.731063,105.721952,17.306511,23.764169,24.757033,29.740340,22.601275,26.691607,1.604697,0.290803
Fairy,271.983942,123.781680,23.587291,29.751298,18.979478,28.548462,29.721130,23.305200,2.147160,0.242536
Fighting,218.565200,102.464378,25.852695,28.290163,18.578163,28.159345,22.745777,26.054567,1.800601,0.000000
Fire,226.262840,109.760496,19.404123,28.769275,23.658200,30.042121,22.619908,25.245783,1.850665,0.297678
Flying,42.437209,161.400124,20.694202,37.500000,21.360009,34.769479,22.173558,32.098806,0.577350,0.577350
Ghost,209.189218,110.072685,31.685895,29.629687,32.551138,32.561217,26.038414,28.020280,1.693203,0.245935
Grass,200.264385,106.650626,19.516564,25.380520,24.485192,27.244864,21.446645,28.506456,1.579173,0.203997

In [292]:
df.groupby(['Type 1']).mean().sort_values('Attack' , ascending = False).head(10)

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,,
Dragon,474.375000,550.531250,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250,3.875000,0.375000
Fighting,363.851852,416.444444,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074,3.370370,0.000000
Ground,356.281250,437.500000,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250,3.156250,0.125000
Rock,392.727273,453.750000,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091,3.454545,0.090909
Steel,442.851852,487.703704,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259,3.851852,0.148148
Dark,461.354839,445.741935,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290,4.032258,0.064516
Fire,327.403846,458.076923,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308,3.211538,0.096154
Flying,677.750000,485.000000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000,5.500000,0.500000
Poison,251.785714,399.142857,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429,2.535714,0.000000
Water,303.089286,430.455357,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286,2.857143,0.035714

In [293]:
df.groupby(['Type 1']).mean().sort_values('Defense' , ascending = False).head(10)

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,,
Steel,442.851852,487.703704,65.222222,92.703704,126.370370,67.518519,80.629630,55.259259,3.851852,0.148148
Rock,392.727273,453.750000,65.363636,92.863636,100.795455,63.340909,75.477273,55.909091,3.454545,0.090909
Dragon,474.375000,550.531250,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250,3.875000,0.375000
Ground,356.281250,437.500000,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250,3.156250,0.125000
Ghost,486.500000,439.562500,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750,4.187500,0.062500
Water,303.089286,430.455357,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286,2.857143,0.035714
Ice,423.541667,433.458333,72.000000,72.750000,71.416667,77.541667,76.291667,63.458333,3.541667,0.083333
Grass,344.871429,421.142857,67.271429,73.214286,70.800000,77.500000,70.428571,61.928571,3.357143,0.042857
Bug,334.492754,378.927536,56.884058,70.971014,70.724638,53.869565,64.797101,61.681159,3.217391,0.000000
Dark,461.354839,445.741935,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290,4.032258,0.064516

In [294]:
df.groupby(['Type 1']).mean().sort_values('Speed' , ascending = False).head(10)

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,,
Flying,677.750000,485.000000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000,5.500000,0.500000
Electric,363.500000,443.409091,59.795455,69.090909,66.295455,90.022727,73.704545,84.500000,3.272727,0.090909
Dragon,474.375000,550.531250,83.312500,112.125000,86.375000,96.843750,88.843750,83.031250,3.875000,0.375000
Psychic,380.807018,475.947368,70.631579,71.456140,67.684211,98.403509,86.280702,81.491228,3.385965,0.245614
Dark,461.354839,445.741935,66.806452,88.387097,70.225806,74.645161,69.516129,76.161290,4.032258,0.064516
Fire,327.403846,458.076923,69.903846,84.769231,67.769231,88.980769,72.211538,74.442308,3.211538,0.096154
Normal,319.173469,401.683673,77.275510,73.469388,59.846939,55.816327,63.724490,71.551020,3.051020,0.020408
Fighting,363.851852,416.444444,69.851852,96.777778,65.925926,53.111111,64.703704,66.074074,3.370370,0.000000
Water,303.089286,430.455357,72.062500,74.151786,72.946429,74.812500,70.517857,65.964286,2.857143,0.035714
Ghost,486.500000,439.562500,64.437500,73.781250,81.187500,79.343750,76.468750,64.343750,4.187500,0.062500

In [295]:
df.sum()

#                                                        290251
Name          BulbasaurIvysaurVenusaurVenusaurMega VenusaurC...
Type 1        GrassGrassGrassGrassFireFireFireFireFireWaterW...
Total                                                    348082
HP                                                        55407
Attack                                                    63201
Defense                                                   59074
Sp. Atk                                                   58256
Sp. Def                                                   57522
Speed                                                     54622
Generation                                                 2659
Legendary                                                    65
dtype: object

In [298]:
df.groupby(['Type 2']).sum().head()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 2,,,,,,,,,,
Bug,1146,1180,160,270,240,140,185,185,10,0
Dark,8277,9688,1511,2196,1441,1636,1397,1507,75,1
Dragon,8686,9471,1479,1700,1567,1773,1502,1450,75,4
Electric,2794,2732,529,436,410,487,441,429,24,1
Fairy,8718,9613,1479,1417,1699,1725,1885,1408,82,2

In [305]:
df.count()

#             800
Name          800
Type 1        800
Type 2        414
Total         800
HP            800
Attack        800
Defense       800
Sp. Atk       800
Sp. Def       800
Speed         800
Generation    800
Legendary     800
dtype: int64

In [306]:
df['count1'] = 0
df.groupby(['Type 2']).count()['count1']

Type 2
Bug          3
Dark        20
Dragon      18
Electric     6
Fairy       23
Fighting    26
Fire        12
Flying      97
Ghost       14
Grass       25
Ground      35
Ice         14
Normal       4
Poison      34
Psychic     33
Rock        14
Steel       22
Water       14
Name: count1, dtype: int64

In [307]:
df['count1'] = 0
df.groupby(['Type 1']).count()['count1']

Type 1
Bug          69
Dark         31
Dragon       32
Electric     44
Fairy        17
Fighting     27
Fire         52
Flying        4
Ghost        32
Grass        70
Ground       32
Ice          24
Normal       98
Poison       28
Psychic      57
Rock         44
Steel        27
Water       112
Name: count1, dtype: int64

In [308]:
df['count1'] = 0
df.groupby(['Type 1' , 'Type 2' , 'Legendary']).count()['count1']

Type 1  Type 2    Legendary
Bug     Electric  False         2
        Fighting  False         2
        Fire      False         2
        Flying    False        14
        Ghost     False         1
                               ..
Water   Ice       False         3
        Poison    False         3
        Psychic   False         5
        Rock      False         4
        Steel     False         1
Name: count1, Length: 150, dtype: int64

# Loading Data in Chunks

In [309]:
for df in pd.read_csv('C:/Users/User/Desktop/Pokemon.csv', chunksize=10):
    print(df)

   #                       Name Type 1  Type 2  Total  HP  Attack  Defense  \
0  1                  Bulbasaur  Grass  Poison    318  45      49       49
1  2                    Ivysaur  Grass  Poison    405  60      62       63
2  3                   Venusaur  Grass  Poison    525  80      82       83
3  3      VenusaurMega Venusaur  Grass  Poison    625  80     100      123
4  4                 Charmander   Fire     NaN    309  39      52       43
5  5                 Charmeleon   Fire     NaN    405  58      64       58
6  6                  Charizard   Fire  Flying    534  78      84       78
7  6  CharizardMega Charizard X   Fire  Dragon    634  78     130      111
8  6  CharizardMega Charizard Y   Fire  Flying    634  78     104       78
9  7                   Squirtle  Water     NaN    314  44      48       65

   Sp. Atk  Sp. Def  Speed  Generation  Legendary
0       65       65     45           1      False
1       80       80     60           1      False
2      100      100     80           1      False
3      122      120     80           1      False
4       60       50     65           1      False
5       80       65     80           1      False
6      109       85    100           1      False
7      130       85    100           1      False
8      159      115    100           1      False
9       50       64     43           1      False
     #                     Name Type 1  Type 2  Total  HP  Attack  Defense  \
10   8                Wartortle  Water     NaN    405  59      63       80
11   9                Blastoise  Water     NaN    530  79      83      100
12   9  BlastoiseMega Blastoise  Water     NaN    630  79     103      120
13  10                 Caterpie    Bug     NaN    195  45      30       35
14  11                  Metapod    Bug     NaN    205  50      20       55
15  12               Butterfree    Bug  Flying    395  60      45       50
16  13                   Weedle    Bug  Poison    195  40      35       30
17  14                   Kakuna    Bug  Poison    205  45      25       50
18  15                 Beedrill    Bug  Poison    395  65      90       40
19  15    BeedrillMega Beedrill    Bug  Poison    495  65     150       40

    Sp. Atk  Sp. Def  Speed  Generation  Legendary
10       65       80     58           1      False
11       85      105     78           1      False
12      135      115     78           1      False
13       20       20     45           1      False
14       25       25     30           1      False
15       90       80     70           1      False
16       20       20     50           1      False
17       25       25     35           1      False
18       45       80     75           1      False
19       15       80    145           1      False
     #                 Name  Type 1  Type 2  Total  HP  Attack  Defense  \
20  16               Pidgey  Normal  Flying    251  40      45       40
21  17            Pidgeotto  Normal  Flying    349  63      60       55
22  18              Pidgeot  Normal  Flying    479  83      80       75
23  18  PidgeotMega Pidgeot  Normal  Flying    579  83      80       80
24  19              Rattata  Normal     NaN    253  30      56       35
25  20             Raticate  Normal     NaN    413  55      81       60
26  21              Spearow  Normal  Flying    262  40      60       30
27  22               Fearow  Normal  Flying    442  65      90       65
28  23                Ekans  Poison     NaN    288  35      60       44
29  24                Arbok  Poison     NaN    438  60      85       69

    Sp. Atk  Sp. Def  Speed  Generation  Legendary
20       35       35     56           1      False
21       50       50     71           1      False
22       70       70    101           1      False
23      135       80    121           1      False
24       25       35     72           1      False
25       50       70     97           1      False
26       31       31     70           1      False
27       61       61    100           1      False
28       40       54     55           1      False
29       65       79     80           1      False
     #       Name    Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  \
30  25    Pikachu  Electric     NaN    320  35      55       40       50
31  26     Raichu  Electric     NaN    485  60      90       55       90
32  27  Sandshrew    Ground     NaN    300  50      75       85       20
33  28  Sandslash    Ground     NaN    450  75     100      110       45
34  29   Nidoran♀    Poison     NaN    275  55      47       52       40
35  30   Nidorina    Poison     NaN    365  70      62       67       55
36  31  Nidoqueen    Poison  Ground    505  90      92       87       75
37  32   Nidoran♂    Poison     NaN    273  46      57       40       40
38  33   Nidorino    Poison     NaN    365  61      72       57       55
39  34   Nidoking    Poison  Ground    505  81     102       77       85

    Sp. Def  Speed  Generation  Legendary
30       50     90           1      False
31       80    110           1      False
32       30     40           1      False
33       55     65           1      False
34       40     41           1      False
35       55     56           1      False
36       85     76           1      False
37       40     50           1      False
38       55     65           1      False
39       75     85           1      False
     #        Name  Type 1  Type 2  Total   HP  Attack  Defense  Sp. Atk  \
40  35    Clefairy   Fairy     NaN    323   70      45       48       60
41  36    Clefable   Fairy     NaN    483   95      70       73       95
42  37      Vulpix    Fire     NaN    299   38      41       40       50
43  38   Ninetales    Fire     NaN    505   73      76       75       81
44  39  Jigglypuff  Normal   Fairy    270  115      45       20       45
45  40  Wigglytuff  Normal   Fairy    435  140      70       45       85
46  41       Zubat  Poison  Flying    245   40      45       35       30
47  42      Golbat  Poison  Flying    455   75      80       70       65
48  43      Oddish   Grass  Poison    320   45      50       55       75
49  44       Gloom   Grass  Poison    395   60      65       70       85

    Sp. Def  Speed  Generation  Legendary
40       65     35           1      False
41       90     60           1      False
42       65     65           1      False
43      100    100           1      False
44       25     20           1      False
45       50     45           1      False
46       40     55           1      False
47       75     90           1      False
48       65     30           1      False
49       75     40           1      False
     #       Name  Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  \
50  45  Vileplume   Grass  Poison    490  75      80       85      110
51  46      Paras     Bug   Grass    285  35      70       55       45
52  47   Parasect     Bug   Grass    405  60      95       80       60
53  48    Venonat     Bug  Poison    305  60      55       50       40
54  49   Venomoth     Bug  Poison    450  70      65       60       90
55  50    Diglett  Ground     NaN    265  10      55       25       35
56  51    Dugtrio  Ground     NaN    405  35      80       50       50
57  52     Meowth  Normal     NaN    290  40      45       35       40
58  53    Persian  Normal     NaN    440  65      70       60       65
59  54    Psyduck   Water     NaN    320  50      52       48       65

    Sp. Def  Speed  Generation  Legendary
50       90     50           1      False
51       55     25           1      False
52       80     30           1      False
53       55     45           1      False
54       75     90           1      False
55       45     95           1      False
56       70    120           1      False
57       40     90           1      False
58       65    115           1      False
59       50     55           1      False
     #       Name    Type 1    Type 2  Total  HP  Attack  Defense  Sp. Atk  \
60  55    Golduck     Water       NaN    500  80      82       78       95
61  56     Mankey  Fighting       NaN    305  40      80       35       35
62  57   Primeape  Fighting       NaN    455  65     105       60       60
63  58  Growlithe      Fire       NaN    350  55      70       45       70
64  59   Arcanine      Fire       NaN    555  90     110       80      100
65  60    Poliwag     Water       NaN    300  40      50       40       40
66  61  Poliwhirl     Water       NaN    385  65      65       65       50
67  62  Poliwrath     Water  Fighting    510  90      95       95       70
68  63       Abra   Psychic       NaN    310  25      20       15      105
69  64    Kadabra   Psychic       NaN    400  40      35       30      120

    Sp. Def  Speed  Generation  Legendary
60       80     85           1      False
61       45     70           1      False
62       70     95           1      False
63       50     60           1      False
64       80     95           1      False
65       40     90           1      False
66       50     90           1      False
67       90     70           1      False
68       55     90           1      False
69       70    105           1      False
     #                   Name    Type 1  Type 2  Total  HP  Attack  Defense  \
70  65               Alakazam   Psychic     NaN    500  55      50       45
71  65  AlakazamMega Alakazam   Psychic     NaN    590  55      50       65
72  66                 Machop  Fighting     NaN    305  70      80       50
73  67                Machoke  Fighting     NaN    405  80     100       70
74  68                Machamp  Fighting     NaN    505  90     130       80
75  69             Bellsprout     Grass  Poison    300  50      75       35
76  70             Weepinbell     Grass  Poison    390  65      90       50
77  71             Victreebel     Grass  Poison    490  80     105       65
78  72              Tentacool     Water  Poison    335  40      40       35
79  73             Tentacruel     Water  Poison    515  80      70       65

    Sp. Atk  Sp. Def  Speed  Generation  Legendary
70      135       95    120           1      False
71      175       95    150           1      False
72       35       35     35           1      False
73       50       60     45           1      False
74       65       85     55           1      False
75       70       30     40           1      False
76       85       45     55           1      False
77      100       70     70           1      False
78       50      100     70           1      False
79       80      120    100           1      False
     #                 Name    Type 1   Type 2  Total  HP  Attack  Defense  \
80  74              Geodude      Rock   Ground    300  40      80      100
81  75             Graveler      Rock   Ground    390  55      95      115
82  76                Golem      Rock   Ground    495  80     120      130
83  77               Ponyta      Fire      NaN    410  50      85       55
84  78             Rapidash      Fire      NaN    500  65     100       70
85  79             Slowpoke     Water  Psychic    315  90      65       65
86  80              Slowbro     Water  Psychic    490  95      75      110
87  80  SlowbroMega Slowbro     Water  Psychic    590  95      75      180
88  81            Magnemite  Electric    Steel    325  25      35       70
89  82             Magneton  Electric    Steel    465  50      60       95

    Sp. Atk  Sp. Def  Speed  Generation  Legendary
80       30       30     20           1      False
81       45       45     35           1      False
82       55       65     45           1      False
83       65       65     90           1      False
84       80       80    105           1      False
85       40       40     15           1      False
86      100       80     30           1      False
87      130       80     30           1      False
88       95       55     45           1      False
89      120       70     70           1      False
     #        Name  Type 1  Type 2  Total   HP  Attack  Defense  Sp. Atk  \
90  83  Farfetch'd  Normal  Flying    352   52      65       55       58
91  84       Doduo  Normal  Flying    310   35      85       45       35
92  85      Dodrio  Normal  Flying    460   60     110       70       60
93  86        Seel   Water     NaN    325   65      45       55       45
94  87     Dewgong   Water     Ice    475   90      70       80       70
95  88      Grimer  Poison     NaN    325   80      80       50       40
96  89         Muk  Poison     NaN    500  105     105       75       65
97  90    Shellder   Water     NaN    305   30      65      100       45
98  91    Cloyster   Water     Ice    525   50      95      180       85
99  92      Gastly   Ghost  Poison    310   30      35       30      100

    Sp. Def  Speed  Generation  Legendary
90       62     60           1      False
91       35     75           1      False
92       60    100           1      False
93       70     45           1      False
94       95     70           1      False
95       50     25           1      False
96      100     50           1      False
97       25     40           1      False
98       45     70           1      False
99       35     80           1      False
       #               Name    Type 1  Type 2  Total  HP  Attack  Defense  \
100   93            Haunter     Ghost  Poison    405  45      50       45
101   94             Gengar     Ghost  Poison    500  60      65       60
102   94  GengarMega Gengar     Ghost  Poison    600  60      65       80
103   95               Onix      Rock  Ground    385  35      45      160
104   96            Drowzee   Psychic     NaN    328  60      48       45
105   97              Hypno   Psychic     NaN    483  85      73       70
106   98             Krabby     Water     NaN    325  30     105       90
107   99            Kingler     Water     NaN    475  55     130      115
108  100            Voltorb  Electric     NaN    330  40      30       50
109  101          Electrode  Electric     NaN    480  60      50       70

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
100      115       55     95           1      False
101      130       75    110           1      False
102      170       95    130           1      False
103       30       45     70           1      False
104       43       90     42           1      False
105       73      115     67           1      False
106       25       25     50           1      False
107       50       50     75           1      False
108       55       55    100           1      False
109       80       80    140           1      False
       #        Name    Type 1   Type 2  Total  HP  Attack  Defense  Sp. Atk  \
110  102   Exeggcute     Grass  Psychic    325  60      40       80       60
111  103   Exeggutor     Grass  Psychic    520  95      95       85      125
112  104      Cubone    Ground      NaN    320  50      50       95       40
113  105     Marowak    Ground      NaN    425  60      80      110       50
114  106   Hitmonlee  Fighting      NaN    455  50     120       53       35
115  107  Hitmonchan  Fighting      NaN    455  50     105       79       35
116  108   Lickitung    Normal      NaN    385  90      55       75       60
117  109     Koffing    Poison      NaN    340  40      65       95       60
118  110     Weezing    Poison      NaN    490  65      90      120       85
119  111     Rhyhorn    Ground     Rock    345  80      85       95       30

     Sp. Def  Speed  Generation  Legendary
110       45     40           1      False
111       65     55           1      False
112       50     35           1      False
113       80     45           1      False
114      110     87           1      False
115      110     76           1      False
116       75     30           1      False
117       45     35           1      False
118       70     60           1      False
119       30     25           1      False
       #                       Name  Type 1 Type 2  Total   HP  Attack  \
120  112                     Rhydon  Ground   Rock    485  105     130
121  113                    Chansey  Normal    NaN    450  250       5
122  114                    Tangela   Grass    NaN    435   65      55
123  115                 Kangaskhan  Normal    NaN    490  105      95
124  115  KangaskhanMega Kangaskhan  Normal    NaN    590  105     125
125  116                     Horsea   Water    NaN    295   30      40
126  117                     Seadra   Water    NaN    440   55      65
127  118                    Goldeen   Water    NaN    320   45      67
128  119                    Seaking   Water    NaN    450   80      92
129  120                     Staryu   Water    NaN    340   30      45

     Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary
120      120       45       45     40           1      False
121        5       35      105     50           1      False
122      115      100       40     60           1      False
123       80       40       80     90           1      False
124      100       60      100    100           1      False
125       70       70       25     60           1      False
126       95       95       45     85           1      False
127       60       35       50     63           1      False
128       65       65       80     68           1      False
129       55       70       55     85           1      False
       #               Name    Type 1   Type 2  Total  HP  Attack  Defense  \
130  121            Starmie     Water  Psychic    520  60      75       85
131  122           Mr. Mime   Psychic    Fairy    460  40      45       65
132  123            Scyther       Bug   Flying    500  70     110       80
133  124               Jynx       Ice  Psychic    455  65      50       35
134  125         Electabuzz  Electric      NaN    490  65      83       57
135  126             Magmar      Fire      NaN    495  65      95       57
136  127             Pinsir       Bug      NaN    500  65     125      100
137  127  PinsirMega Pinsir       Bug   Flying    600  65     155      120
138  128             Tauros    Normal      NaN    490  75     100       95
139  129           Magikarp     Water      NaN    200  20      10       55

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
130      100       85    115           1      False
131      100      120     90           1      False
132       55       80    105           1      False
133      115       95     95           1      False
134       95       85    105           1      False
135      100       85     93           1      False
136       55       70     85           1      False
137       65       90    105           1      False
138       40       70    110           1      False
139       15       20     80           1      False
       #                   Name    Type 1  Type 2  Total   HP  Attack  \
140  130               Gyarados     Water  Flying    540   95     125
141  130  GyaradosMega Gyarados     Water    Dark    640   95     155
142  131                 Lapras     Water     Ice    535  130      85
143  132                  Ditto    Normal     NaN    288   48      48
144  133                  Eevee    Normal     NaN    325   55      55
145  134               Vaporeon     Water     NaN    525  130      65
146  135                Jolteon  Electric     NaN    525   65      65
147  136                Flareon      Fire     NaN    525   65     130
148  137                Porygon    Normal     NaN    395   65      60
149  138                Omanyte      Rock   Water    355   35      40

     Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary
140       79       60      100     81           1      False
141      109       70      130     81           1      False
142       80       85       95     60           1      False
143       48       48       48     48           1      False
144       50       45       65     55           1      False

       #                     Name    Type 1  Type 2  Total   HP  Attack  \
260  241                  Miltank    Normal     NaN    490   95      80
261  242                  Blissey    Normal     NaN    540  255      10
262  243                   Raikou  Electric     NaN    580   90      85
263  244                    Entei      Fire     NaN    580  115     115
264  245                  Suicune     Water     NaN    580  100      75
265  246                 Larvitar      Rock  Ground    300   50      64
266  247                  Pupitar      Rock  Ground    410   70      84
267  248                Tyranitar      Rock    Dark    600  100     134
268  248  TyranitarMega Tyranitar      Rock    Dark    700  100     164
269  249                    Lugia   Psychic  Flying    680  106      90

     Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary
260      105       40       70    100           2      False
261       10       75      135     55           2      False
262       75      115      100    115           2       True
263       85       90       75    100           2       True
264      115       90      115     85           2       True
265       50       45       50     41           2      False
266       70       65       70     51           2      False
267      110       95      100     61           2      False
268      150       95      120     71           2      False
269      130       90      154    110           2       True
       #                   Name   Type 1    Type 2  Total   HP  Attack  \
270  250                  Ho-oh     Fire    Flying    680  106     130
271  251                 Celebi  Psychic     Grass    600  100     100
272  252                Treecko    Grass       NaN    310   40      45
273  253                Grovyle    Grass       NaN    405   50      65
274  254               Sceptile    Grass       NaN    530   70      85
275  254  SceptileMega Sceptile    Grass    Dragon    630   70     110
276  255                Torchic     Fire       NaN    310   45      60
277  256              Combusken     Fire  Fighting    405   60      85
278  257               Blaziken     Fire  Fighting    530   80     120
279  257  BlazikenMega Blaziken     Fire  Fighting    630   80     160

     Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary
270       90      110      154     90           2       True
271      100      100      100    100           2      False
272       35       65       55     70           3      False
273       45       85       65     95           3      False
274       65      105       85    120           3      False
275       75      145       85    145           3      False
276       40       70       50     45           3      False
277       60       85       60     55           3      False
278       70      110       70     80           3      False
279       80      130       80    100           3      False
       #                   Name  Type 1  Type 2  Total   HP  Attack  Defense  \
280  258                 Mudkip   Water     NaN    310   50      70       50
281  259              Marshtomp   Water  Ground    405   70      85       70
282  260               Swampert   Water  Ground    535  100     110       90
283  260  SwampertMega Swampert   Water  Ground    635  100     150      110
284  261              Poochyena    Dark     NaN    220   35      55       35
285  262              Mightyena    Dark     NaN    420   70      90       70
286  263              Zigzagoon  Normal     NaN    240   38      30       41
287  264                Linoone  Normal     NaN    420   78      70       61
288  265                Wurmple     Bug     NaN    195   45      45       35
289  266                Silcoon     Bug     NaN    205   50      35       55

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
280       50       50     40           3      False
281       60       70     50           3      False
282       85       90     60           3      False
283       95      110     70           3      False
284       30       30     35           3      False
285       60       60     70           3      False
286       30       41     60           3      False
287       50       61    100           3      False
288       20       30     20           3      False
289       25       25     15           3      False
       #       Name  Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  \
290  267  Beautifly     Bug  Flying    395  60      70       50      100
291  268    Cascoon     Bug     NaN    205  50      35       55       25
292  269     Dustox     Bug  Poison    385  60      50       70       50
293  270      Lotad   Water   Grass    220  40      30       30       40
294  271     Lombre   Water   Grass    340  60      50       50       60
295  272   Ludicolo   Water   Grass    480  80      70       70       90
296  273     Seedot   Grass     NaN    220  40      40       50       30
297  274    Nuzleaf   Grass    Dark    340  70      70       40       60
298  275    Shiftry   Grass    Dark    480  90     100       60       90
299  276    Taillow  Normal  Flying    270  40      55       30       30

     Sp. Def  Speed  Generation  Legendary
290       50     65           3      False
291       25     15           3      False
292       90     65           3      False
293       50     30           3      False
294       70     50           3      False
295      100     70           3      False
296       30     30           3      False
297       40     60           3      False
298       60     80           3      False
299       30     85           3      False
       #                     Name   Type 1  Type 2  Total  HP  Attack  \
300  277                  Swellow   Normal  Flying    430  60      85
301  278                  Wingull    Water  Flying    270  40      30
302  279                 Pelipper    Water  Flying    430  60      50
303  280                    Ralts  Psychic   Fairy    198  28      25
304  281                   Kirlia  Psychic   Fairy    278  38      35
305  282                Gardevoir  Psychic   Fairy    518  68      65
306  282  GardevoirMega Gardevoir  Psychic   Fairy    618  68      85
307  283                  Surskit      Bug   Water    269  40      30
308  284               Masquerain      Bug  Flying    414  70      60
309  285                Shroomish    Grass     NaN    295  60      40

     Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary
300       60       50       50    125           3      False
301       30       55       30     85           3      False
302      100       85       70     65           3      False
303       25       45       35     40           3      False
304       35       65       55     50           3      False
305       65      125      115     80           3      False
306       65      165      135    100           3      False
307       32       50       52     65           3      False
308       62       80       82     60           3      False
309       60       40       60     35           3      False
       #      Name  Type 1    Type 2  Total   HP  Attack  Defense  Sp. Atk  \
310  286   Breloom   Grass  Fighting    460   60     130       80       60
311  287   Slakoth  Normal       NaN    280   60      60       60       35
312  288  Vigoroth  Normal       NaN    440   80      80       80       55
313  289   Slaking  Normal       NaN    670  150     160      100       95
314  290   Nincada     Bug    Ground    266   31      45       90       30
315  291   Ninjask     Bug    Flying    456   61      90       45       50
316  292  Shedinja     Bug     Ghost    236    1      90       45       30
317  293   Whismur  Normal       NaN    240   64      51       23       51
318  294   Loudred  Normal       NaN    360   84      71       43       71
319  295   Exploud  Normal       NaN    490  104      91       63       91

     Sp. Def  Speed  Generation  Legendary
310       60     70           3      False
311       35     30           3      False
312       55     90           3      False
313       65    100           3      False
314       30     40           3      False
315       50    160           3      False
316       30     40           3      False
317       23     28           3      False
318       43     48           3      False
319       73     68           3      False
       #                 Name    Type 1 Type 2  Total   HP  Attack  Defense  \
320  296             Makuhita  Fighting    NaN    237   72      60       30
321  297             Hariyama  Fighting    NaN    474  144     120       60
322  298              Azurill    Normal  Fairy    190   50      20       40
323  299             Nosepass      Rock    NaN    375   30      45      135
324  300               Skitty    Normal    NaN    260   50      45       45
325  301             Delcatty    Normal    NaN    380   70      65       65
326  302              Sableye      Dark  Ghost    380   50      75       75
327  302  SableyeMega Sableye      Dark  Ghost    480   50      85      125
328  303               Mawile     Steel  Fairy    380   50      85       85
329  303    MawileMega Mawile     Steel  Fairy    480   50     105      125

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
320       20       30     25           3      False
321       40       60     50           3      False
322       20       40     20           3      False
323       45       90     30           3      False
324       35       35     50           3      False
325       55       55     70           3      False
326       65       65     50           3      False
327       85      115     20           3      False
328       55       55     50           3      False
329       55       95     50           3      False
       #                     Name    Type 1   Type 2  Total  HP  Attack  \
330  304                     Aron     Steel     Rock    330  50      70
331  305                   Lairon     Steel     Rock    430  60      90
332  306                   Aggron     Steel     Rock    530  70     110
333  306        AggronMega Aggron     Steel      NaN    630  70     140
334  307                 Meditite  Fighting  Psychic    280  30      40
335  308                 Medicham  Fighting  Psychic    410  60      60
336  308    MedichamMega Medicham  Fighting  Psychic    510  60     100
337  309                Electrike  Electric      NaN    295  40      45
338  310                Manectric  Electric      NaN    475  70      75
339  310  ManectricMega Manectric  Electric      NaN    575  70      75

     Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary
330      100       40       40     30           3      False
331      140       50       50     40           3      False
332      180       60       60     50           3      False
333      230       60       80     50           3      False
334       55       40       55     60           3      False
335       75       60       75     80           3      False
336       85       80       85    100           3      False
337       40       65       40     65           3      False
338       60      105       60    105           3      False
339       80      135       80    135           3      False
       #                   Name    Type 1  Type 2  Total   HP  Attack  \
340  311                 Plusle  Electric     NaN    405   60      50
341  312                  Minun  Electric     NaN    405   60      40
342  313                Volbeat       Bug     NaN    400   65      73
343  314               Illumise       Bug     NaN    400   65      47
344  315                Roselia     Grass  Poison    400   50      60
345  316                 Gulpin    Poison     NaN    302   70      43
346  317                 Swalot    Poison     NaN    467  100      73
347  318               Carvanha     Water    Dark    305   45      90
348  319               Sharpedo     Water    Dark    460   70     120
349  319  SharpedoMega Sharpedo     Water    Dark    560   70     140

     Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary
340       40       85       75     95           3      False
341       50       75       85     95           3      False
342       55       47       75     85           3      False
343       55       73       75     85           3      False
344       45      100       80     65           3      False
345       53       43       53     40           3      False
346       83       73       83     55           3      False
347       20       65       20     65           3      False
348       40       95       40     95           3      False
349       70      110       65    105           3      False
       #                   Name   Type 1  Type 2  Total   HP  Attack  Defense  \
350  320                Wailmer    Water     NaN    400  130      70       35
351  321                Wailord    Water     NaN    500  170      90       45
352  322                  Numel     Fire  Ground    305   60      60       40
353  323               Camerupt     Fire  Ground    460   70     100       70
354  323  CameruptMega Camerupt     Fire  Ground    560   70     120      100
355  324                Torkoal     Fire     NaN    470   70      85      140
356  325                 Spoink  Psychic     NaN    330   60      25       35
357  326                Grumpig  Psychic     NaN    470   80      45       65
358  327                 Spinda   Normal     NaN    360   60      60       60
359  328               Trapinch   Ground     NaN    290   45     100       45

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
350       70       35     60           3      False
351       90       45     60           3      False
352       65       45     35           3      False
353      105       75     40           3      False
354      145      105     20           3      False
355       85       70     20           3      False
356       70       80     60           3      False
357       90      110     80           3      False
358       60       60     60           3      False
359       45       45     10           3      False
       #                 Name  Type 1   Type 2  Total  HP  Attack  Defense  \
360  329              Vibrava  Ground   Dragon    340  50      70       50
361  330               Flygon  Ground   Dragon    520  80     100       80
362  331               Cacnea   Grass      NaN    335  50      85       40
363  332             Cacturne   Grass     Dark    475  70     115       60
364  333               Swablu  Normal   Flying    310  45      40       60
365  334              Altaria  Dragon   Flying    490  75      70       90
366  334  AltariaMega Altaria  Dragon    Fairy    590  75     110      110
367  335             Zangoose  Normal      NaN    458  73     115       60
368  336              Seviper  Poison      NaN    458  73     100       60
369  337             Lunatone    Rock  Psychic    440  70      55       65

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
360       50       50     70           3      False
361       80       80    100           3      False
362       85       40     35           3      False
363      115       60     55           3      False
364       40       75     50           3      False
365       70      105     80           3      False
366      110      105     80           3      False
367       60       60     90           3      False
368      100       60     65           3      False
369       95       85     70           3      False
       #       Name  Type 1   Type 2  Total   HP  Attack  Defense  Sp. Atk  \
370  338    Solrock    Rock  Psychic    440   70      95       85       55
371  339   Barboach   Water   Ground    288   50      48       43       46
372  340   Whiscash   Water   Ground    468  110      78       73       76
373  341   Corphish   Water      NaN    308   43      80       65       50
374  342  Crawdaunt   Water     Dark    468   63     120       85       90
375  343     Baltoy  Ground  Psychic    300   40      40       55       40
376  344    Claydol  Ground  Psychic    500   60      70      105       70
377  345     Lileep    Rock    Grass    355   66      41       77       61
378  346    Cradily    Rock    Grass    495   86      81       97       81
379  347    Anorith    Rock      Bug    355   45      95       50       40

     Sp. Def  Speed  Generation  Legendary
370       65     70           3      False
371       41     60           3      False
372       71     60           3      False
373       35     35           3      False
374       55     55           3      False
375       70     55           3      False
376      120     75           3      False
377       87     23           3      False
378      107     43           3      False
379       50     75           3      False
       #                 Name  Type 1 Type 2  Total  HP  Attack  Defense  \
380  348              Armaldo    Rock    Bug    495  75     125      100
381  349               Feebas   Water    NaN    200  20      15       20
382  350              Milotic   Water    NaN    540  95      60       79
383  351             Castform  Normal    NaN    420  70      70       70
384  352              Kecleon  Normal    NaN    440  60      90       70
385  353              Shuppet   Ghost    NaN    295  44      75       35
386  354              Banette   Ghost    NaN    455  64     115       65
387  354  BanetteMega Banette   Ghost    NaN    555  64     165       75
388  355              Duskull   Ghost    NaN    295  20      40       90
389  356             Dusclops   Ghost    NaN    455  40      70      130

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
380       70       80     45           3      False
381       10       55     80           3      False
382      100      125     81           3      False
383       70       70     70           3      False
384       60      120     40           3      False
385       63       33     45           3      False
386       83       63     65           3      False
387       93       83     75           3      False
388       30       90     25           3      False
389       60      130     25           3      False
       #               Name   Type 1  Type 2  Total  HP  Attack  Defense  \
390  357            Tropius    Grass  Flying    460  99      68       83
391  358           Chimecho  Psychic     NaN    425  65      50       70
392  359              Absol     Dark     NaN    465  65     130       60
393  359    AbsolMega Absol     Dark     NaN    565  65     150       60
394  360             Wynaut  Psychic     NaN    260  95      23       48
395  361            Snorunt      Ice     NaN    300  50      50       50
396  362             Glalie      Ice     NaN    480  80      80       80
397  362  GlalieMega Glalie      Ice     NaN    580  80     120       80
398  363             Spheal      Ice   Water    290  70      40       50
399  364             Sealeo      Ice   Water    410  90      60       70

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
390       72       87     51           3      False
391       95       80     65           3      False
392       75       60     75           3      False
393      115       60    115           3      False
394       23       48     23           3      False
395       50       50     50           3      False
396       80       80     80           3      False
397      120       80    100           3      False
398       55       50     25           3      False
399       75       70     45           3      False
       #                     Name  Type 1  Type 2  Total   HP  Attack  \
400  365                  Walrein     Ice   Water    530  110      80
401  366                 Clamperl   Water     NaN    345   35      64
402  367                  Huntail   Water     NaN    485   55     104
403  368                 Gorebyss   Water     NaN    485   55      84

       #                   Name    Type 1  Type 2  Total   HP  Attack  \
490  442              Spiritomb     Ghost    Dark    485   50      92
491  443                  Gible    Dragon  Ground    300   58      70
492  444                 Gabite    Dragon  Ground    410   68      90
493  445               Garchomp    Dragon  Ground    600  108     130
494  445  GarchompMega Garchomp    Dragon  Ground    700  108     170
495  446               Munchlax    Normal     NaN    390  135      85
496  447                  Riolu  Fighting     NaN    285   40      70
497  448                Lucario  Fighting   Steel    525   70     110
498  448    LucarioMega Lucario  Fighting   Steel    625   70     145
499  449             Hippopotas    Ground     NaN    330   68      72

     Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary
490      108       92      108     35           4      False
491       45       40       45     42           4      False
492       65       50       55     82           4      False
493       95       80       85    102           4      False
494      115      120       95     92           4      False
495       40       40       85      5           4      False
496       40       35       40     60           4      False
497       70      115       70     90           4      False
498       88      140       70    112           4      False
499       78       38       42     32           4      False
       #       Name  Type 1    Type 2  Total   HP  Attack  Defense  Sp. Atk  \
500  450  Hippowdon  Ground       NaN    525  108     112      118       68
501  451    Skorupi  Poison       Bug    330   40      50       90       30
502  452    Drapion  Poison      Dark    500   70      90      110       60
503  453   Croagunk  Poison  Fighting    300   48      61       40       61
504  454  Toxicroak  Poison  Fighting    490   83     106       65       86
505  455  Carnivine   Grass       NaN    454   74     100       72       90
506  456    Finneon   Water       NaN    330   49      49       56       49
507  457   Lumineon   Water       NaN    460   69      69       76       69
508  458    Mantyke   Water    Flying    345   45      20       50       60
509  459     Snover   Grass       Ice    334   60      62       50       62

     Sp. Def  Speed  Generation  Legendary
500       72     47           4      False
501       55     65           4      False
502       75     95           4      False
503       40     50           4      False
504       65     85           4      False
505       72     46           4      False
506       61     66           4      False
507       86     91           4      False
508      120     50           4      False
509       60     40           4      False
       #                     Name    Type 1  Type 2  Total   HP  Attack  \
510  460                Abomasnow     Grass     Ice    494   90      92
511  460  AbomasnowMega Abomasnow     Grass     Ice    594   90     132
512  461                  Weavile      Dark     Ice    510   70     120
513  462                Magnezone  Electric   Steel    535   70      70
514  463               Lickilicky    Normal     NaN    515  110      85
515  464                Rhyperior    Ground    Rock    535  115     140
516  465                Tangrowth     Grass     NaN    535  100     100
517  466               Electivire  Electric     NaN    540   75     123
518  467                Magmortar      Fire     NaN    540   75      95
519  468                 Togekiss     Fairy  Flying    545   85      50

     Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary
510       75       92       85     60           4      False
511      105      132      105     30           4      False
512       65       45       85    125           4      False
513      115      130       90     60           4      False
514       95       80       95     50           4      False
515      130       55       55     40           4      False
516      125      110       50     50           4      False
517       67       95       85     95           4      False
518       67      125       95     83           4      False
519       95      120      115     80           4      False
       #                 Name   Type 1    Type 2  Total   HP  Attack  Defense  \
520  469              Yanmega      Bug    Flying    515   86      76       86
521  470              Leafeon    Grass       NaN    525   65     110      130
522  471              Glaceon      Ice       NaN    525   65      60      110
523  472              Gliscor   Ground    Flying    510   75      95      125
524  473            Mamoswine      Ice    Ground    530  110     130       80
525  474            Porygon-Z   Normal       NaN    535   85      80       70
526  475              Gallade  Psychic  Fighting    518   68     125       65
527  475  GalladeMega Gallade  Psychic  Fighting    618   68     165       95
528  476            Probopass     Rock     Steel    525   60      55      145
529  477             Dusknoir    Ghost       NaN    525   45     100      135

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
520      116       56     95           4      False
521       60       65     95           4      False
522      130       95     65           4      False
523       45       75     95           4      False
524       70       60     80           4      False
525      135       75     90           4      False
526       65      115     80           4      False
527       65      115    110           4      False
528       75      150     40           4      False
529       65      135     45           4      False
       #              Name    Type 1  Type 2  Total  HP  Attack  Defense  \
530  478          Froslass       Ice   Ghost    480  70      80       70
531  479             Rotom  Electric   Ghost    440  50      50       77
532  479   RotomHeat Rotom  Electric    Fire    520  50      65      107
533  479   RotomWash Rotom  Electric   Water    520  50      65      107
534  479  RotomFrost Rotom  Electric     Ice    520  50      65      107
535  479    RotomFan Rotom  Electric  Flying    520  50      65      107
536  479    RotomMow Rotom  Electric   Grass    520  50      65      107
537  480              Uxie   Psychic     NaN    580  75      75      130
538  481           Mesprit   Psychic     NaN    580  80     105      105
539  482             Azelf   Psychic     NaN    580  75     125       70

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
530       80       70    110           4      False
531       95       77     91           4      False
532      105      107     86           4      False
533      105      107     86           4      False
534      105      107     86           4      False
535      105      107     86           4      False
536      105      107     86           4      False
537       75      130     95           4       True
538      105      105     80           4       True
539      125       70    115           4       True
       #                   Name   Type 1  Type 2  Total   HP  Attack  Defense  \
540  483                 Dialga    Steel  Dragon    680  100     120      120
541  484                 Palkia    Water  Dragon    680   90     120      100
542  485                Heatran     Fire   Steel    600   91      90      106
543  486              Regigigas   Normal     NaN    670  110     160      110
544  487  GiratinaAltered Forme    Ghost  Dragon    680  150     100      120
545  487   GiratinaOrigin Forme    Ghost  Dragon    680  150     120      100
546  488              Cresselia  Psychic     NaN    600  120      70      120
547  489                 Phione    Water     NaN    480   80      80       80
548  490                Manaphy    Water     NaN    600  100     100      100
549  491                Darkrai     Dark     NaN    600   70      90       90

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
540      150      100     90           4       True
541      150      120    100           4       True
542      130      106     77           4       True
543       80      110    100           4       True
544      100      120     90           4       True
545      120      100     90           4       True
546       75      130     85           4      False
547       80       80     80           4      False
548      100      100    100           4      False
549      135       90    125           4       True
       #               Name   Type 1    Type 2  Total   HP  Attack  Defense  \
550  492  ShayminLand Forme    Grass       NaN    600  100     100      100
551  492   ShayminSky Forme    Grass    Flying    600  100     103       75
552  493             Arceus   Normal       NaN    720  120     120      120
553  494            Victini  Psychic      Fire    600  100     100      100
554  495              Snivy    Grass       NaN    308   45      45       55
555  496            Servine    Grass       NaN    413   60      60       75
556  497          Serperior    Grass       NaN    528   75      75       95
557  498              Tepig     Fire       NaN    308   65      63       45
558  499            Pignite     Fire  Fighting    418   90      93       55
559  500             Emboar     Fire  Fighting    528  110     123       65

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
550      100      100    100           4       True
551      120       75    127           4       True
552      120      120    120           4       True
553      100      100    100           5       True
554       45       55     63           5      False
555       60       75     83           5      False
556       75       95    113           5      False
557       45       45     45           5      False
558       70       55     55           5      False
559      100       65     65           5      False
       #       Name  Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  \
560  501   Oshawott   Water     NaN    308  55      55       45       63
561  502     Dewott   Water     NaN    413  75      75       60       83
562  503   Samurott   Water     NaN    528  95     100       85      108
563  504     Patrat  Normal     NaN    255  45      55       39       35
564  505    Watchog  Normal     NaN    420  60      85       69       60
565  506   Lillipup  Normal     NaN    275  45      60       45       25
566  507    Herdier  Normal     NaN    370  65      80       65       35
567  508  Stoutland  Normal     NaN    500  85     110       90       45
568  509   Purrloin    Dark     NaN    281  41      50       37       50
569  510    Liepard    Dark     NaN    446  64      88       50       88

     Sp. Def  Speed  Generation  Legendary
560       45     45           5      False
561       60     60           5      False
562       70     70           5      False
563       39     42           5      False
564       69     77           5      False
565       45     55           5      False
566       65     60           5      False
567       90     80           5      False
568       37     66           5      False
569       50    106           5      False
       #       Name   Type 1  Type 2  Total   HP  Attack  Defense  Sp. Atk  \
570  511    Pansage    Grass     NaN    316   50      53       48       53
571  512   Simisage    Grass     NaN    498   75      98       63       98
572  513    Pansear     Fire     NaN    316   50      53       48       53
573  514   Simisear     Fire     NaN    498   75      98       63       98
574  515    Panpour    Water     NaN    316   50      53       48       53
575  516   Simipour    Water     NaN    498   75      98       63       98
576  517      Munna  Psychic     NaN    292   76      25       45       67
577  518   Musharna  Psychic     NaN    487  116      55       85      107
578  519     Pidove   Normal  Flying    264   50      55       50       36
579  520  Tranquill   Normal  Flying    358   62      77       62       50

     Sp. Def  Speed  Generation  Legendary
570       48     64           5      False
571       63    101           5      False
572       48     64           5      False
573       63    101           5      False
574       48     64           5      False
575       63    101           5      False
576       55     24           5      False
577       95     29           5      False
578       30     43           5      False
579       42     65           5      False
       #        Name    Type 1  Type 2  Total   HP  Attack  Defense  Sp. Atk  \
580  521    Unfezant    Normal  Flying    488   80     115       80       65
581  522     Blitzle  Electric     NaN    295   45      60       32       50
582  523   Zebstrika  Electric     NaN    497   75     100       63       80
583  524  Roggenrola      Rock     NaN    280   55      75       85       25
584  525     Boldore      Rock     NaN    390   70     105      105       50
585  526    Gigalith      Rock     NaN    515   85     135      130       60
586  527      Woobat   Psychic  Flying    313   55      45       43       55
587  528     Swoobat   Psychic  Flying    425   67      57       55       77
588  529     Drilbur    Ground     NaN    328   60      85       40       30
589  530   Excadrill    Ground   Steel    508  110     135       60       50

     Sp. Def  Speed  Generation  Legendary
580       55     93           5      False
581       32     76           5      False
582       63    116           5      False
583       25     15           5      False
584       40     20           5      False
585       80     25           5      False
586       43     72           5      False
587       55    114           5      False
588       45     68           5      False
589       65     88           5      False
       #               Name    Type 1  Type 2  Total   HP  Attack  Defense  \
590  531             Audino    Normal     NaN    445  103      60       86
591  531  AudinoMega Audino    Normal   Fairy    545  103      60      126
592  532            Timburr  Fighting     NaN    305   75      80       55
593  533            Gurdurr  Fighting     NaN    405   85     105       85
594  534         Conkeldurr  Fighting     NaN    505  105     140       95
595  535            Tympole     Water     NaN    294   50      50       40
596  536          Palpitoad     Water  Ground    384   75      65       55
597  537         Seismitoad     Water  Ground    509  105      95       75
598  538              Throh  Fighting     NaN    465  120     100       85
599  539               Sawk  Fighting     NaN    465   75     125       75

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
590       60       86     50           5      False
591       80      126     50           5      False
592       25       35     35           5      False
593       40       50     40           5      False
594       55       65     45           5      False
595       50       40     64           5      False
596       65       55     69           5      False
597       85       75     74           5      False
598       30       85     45           5      False
599       30       75     85           5      False
       #        Name Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  \
600  540    Sewaddle    Bug   Grass    310  45      53       70       40
601  541    Swadloon    Bug   Grass    380  55      63       90       50
602  542    Leavanny    Bug   Grass    500  75     103       80       70
603  543    Venipede    Bug  Poison    260  30      45       59       30
604  544  Whirlipede    Bug  Poison    360  40      55       99       40
605  545   Scolipede    Bug  Poison    485  60     100       89       55
606  546    Cottonee  Grass   Fairy    280  40      27       60       37
607  547  Whimsicott  Grass   Fairy    480  60      67       85       77
608  548     Petilil  Grass     NaN    280  45      35       50       70
609  549   Lilligant  Grass     NaN    480  70      60       75      110

     Sp. Def  Speed  Generation  Legendary
600       60     42           5      False
601       80     42           5      False
602       80     92           5      False
603       39     57           5      False
604       79     47           5      False
605       69    112           5      False
606       50     66           5      False
607       75    116           5      False
608       50     30           5      False
609       75     90           5      False
       #                     Name  Type 1   Type 2  Total   HP  Attack  \
610  550                 Basculin   Water      NaN    460   70      92
611  551                  Sandile  Ground     Dark    292   50      72
612  552                 Krokorok  Ground     Dark    351   60      82
613  553               Krookodile  Ground     Dark    519   95     117
614  554                 Darumaka    Fire      NaN    315   70      90
615  555  DarmanitanStandard Mode    Fire      NaN    480  105     140
616  555       DarmanitanZen Mode    Fire  Psychic    540  105      30
617  556                 Maractus   Grass      NaN    461   75      86
618  557                  Dwebble     Bug     Rock    325   50      65
619  558                  Crustle     Bug     Rock    475   70      95

     Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary
610       65       80       55     98           5      False
611       35       35       35     65           5      False
612       45       45       45     74           5      False
613       80       65       70     92           5      False
614       45       15       45     50           5      False
615       55       30       55     95           5      False
616      105      140      105     55           5      False
617       67      106       67     60           5      False
618       85       35       35     55           5      False
619      125       65       75     45           5      False
       #        Name   Type 1    Type 2  Total  HP  Attack  Defense  Sp. Atk  \
620  559     Scraggy     Dark  Fighting    348  50      75       70       35
621  560     Scrafty     Dark  Fighting    488  65      90      115       45
622  561    Sigilyph  Psychic    Flying    490  72      58       80      103
623  562      Yamask    Ghost       NaN    303  38      30       85       55
624  563  Cofagrigus    Ghost       NaN    483  58      50      145       95
625  564    Tirtouga    Water      Rock    355  54      78      103       53
626  565  Carracosta    Water      Rock    495  74     108      133       83
627  566      Archen     Rock    Flying    401  55     112       45       74
628  567    Archeops     Rock    Flying    567  75     140       65      112
629  568    Trubbish   Poison       NaN    329  50      50       62       40

     Sp. Def  Speed  Generation  Legendary
620       70     48           5      False
621      115     58           5      False
622       80     97           5      False
623       65     30           5      False
624      105     30           5      False
625       45     22           5      False
626       65     32           5      False
627       45     70           5      False
628       65    110           5      False
629       62     65           5      False
       #        Name   Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  \
630  569    Garbodor   Poison     NaN    474  80      95       82       60
631  570       Zorua     Dark     NaN    330  40      65       40       80
632  571     Zoroark     Dark     NaN    510  60     105       60      120
633  572    Minccino   Normal     NaN    300  55      50       40       40
634  573    Cinccino   Normal     NaN    470  75      95       60       65
635  574     Gothita  Psychic     NaN    290  45      30       50       55
636  575   Gothorita  Psychic     NaN    390  60      45       70       75
637  576  Gothitelle  Psychic     NaN    490  70      55       95       95

799      130       90     70           6       True

In [310]:
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
790,714,Noibat,Flying,Dragon,245,40,30,35,45,40,55,6,False
791,715,Noivern,Flying,Dragon,535,85,70,80,97,80,123,6,False
792,716,Xerneas,Fairy,NaN,680,126,131,95,131,98,99,6,True
793,717,Yveltal,Dark,Flying,680,126,131,95,131,98,99,6,True
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [311]:
df1 = pd.DataFrame()
for df in pd.read_csv('C:/Users/User/Desktop/Pokemon.csv', chunksize=10):
    df1 = pd.concat([df1 ,df])
df1.head(15)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False
10,8,Wartortle,Water,NaN,405,59,63,80,65,80,58,1,False
11,9,Blastoise,Water,NaN,530,79,83,100,85,105,78,1,False
12,9,BlastoiseMega Blastoise,Water,NaN,630,79,103,120,135,115,78,1,False
13,10,Caterpie,Bug,NaN,195,45,30,35,20,20,45,1,False
14,11,Metapod,Bug,NaN,205,50,20,55,25,25,30,1,False

# Stack & unstack in Pandas

In [312]:
col = pd.MultiIndex.from_product([['2010','2015'],['Literacy' , 'GDP']])

data =([[80,7,88,6],[90,8,92,7],[89,7,91,8],[87,6,93,8]])

df6 = pd.DataFrame(data, index=['India','USA' , 'Russia' , 'China'], columns=col)
df6

           2010         2015
       Literacy GDP Literacy GDP
India        80   7       88   6
USA          90   8       92   7
Russia       89   7       91   8
China        87   6       93   8

In [313]:
# Stack() Function stacks the columns to rows.
st_df = df6.stack()
st_df

                 2010  2015
India  GDP          7     6
       Literacy    80    88
USA    GDP          8     7
       Literacy    90    92
Russia GDP          7     8
       Literacy    89    91
China  GDP          6     8
       Literacy    87    93

In [314]:
#Unstacks the row to columns
unst_df = st_df.unstack()
unst_df

       2010          2015
        GDP Literacy  GDP Literacy
China     6       87    8       93
India     7       80    6       88
Russia    7       89    8       91
USA       8       90    7       92

In [315]:
unst_df = unst_df.unstack()
unst_df

2010  GDP       China      6
                India      7
                Russia     7
                USA        8
      Literacy  China     87
                India     80
                Russia    89
                USA       90
2015  GDP       China      8
                India      6
                Russia     8
                USA        7
      Literacy  China     93
                India     88
                Russia    91
                USA       92
dtype: int64

In [316]:
unst_df = unst_df.unstack()
unst_df

               China  India  Russia  USA
2010 GDP           6      7       7    8
     Literacy     87     80      89   90
2015 GDP           8      6       8    7
     Literacy     93     88      91   92

# PIVOT Tables

In [317]:
data = {
    'Country':['India','USA' , 'Russia' , 'China','India','USA' , 'Russia' , 'China','India','USA' , 'Russia' , 'China','India','USA' , 'Russia' , 'China'],
    'Year':['2010','2010','2010','2010' , '2010','2010','2010','2010','2015','2015','2015','2015','2015','2015','2015','2015'],
     
    'Literacy/GDP':['GDP' , 'GDP' , 'GDP' , 'GDP','Literacy' , 'Literacy', 'Literacy' , 'Literacy','GDP' , 'GDP','GDP' , 'GDP','Literacy' , 'Literacy','Literacy' , 'Literacy'],
   'Value':[7,8,7,6,80,90,89,87,6,7,8, 8, 88 , 92 , 91 ,93]}
 
df7 = pd.DataFrame(data,columns=['Country','Year','Literacy/GDP','Value'])
df7

   Country  Year Literacy/GDP  Value
0    India  2010          GDP      7
1      USA  2010          GDP      8
2   Russia  2010          GDP      7
3    China  2010          GDP      6
4    India  2010     Literacy     80
5      USA  2010     Literacy     90
6   Russia  2010     Literacy     89
7    China  2010     Literacy     87
8    India  2015          GDP      6
9      USA  2015          GDP      7
10  Russia  2015          GDP      8
11   China  2015          GDP      8
12   India  2015     Literacy     88
13     USA  2015     Literacy     92
14  Russia  2015     Literacy     91
15   China  2015     Literacy     93

In [318]:
# Pivot table with SUM aggregation
pd.pivot_table(df7 , index= ['Year' , 'Literacy/GDP'] , aggfunc='sum')

                   Value
Year Literacy/GDP
2010 GDP              28
     Literacy        346
2015 GDP              29
     Literacy        364

In [ ]:
# Pivot table with MEAN aggregation
pd.pivot_table(df7 , index= ['Year' , 'Literacy/GDP'] , aggfunc='mean')

# Hierarchical indexing

In [ ]:
df7

In [ ]:
df8=df7.set_index(['Year', 'Literacy/GDP'])
df8

In [ ]:
df8.index

In [ ]:
df8.loc['2010']

In [ ]:
df8.loc[['2010']]

In [ ]:
df8.loc['2015','Literacy']

In [ ]:
df8.loc['2015','Literacy']

In [ ]:
df8=df7.set_index(['Year', 'Literacy/GDP' , 'Country'])
df8

### SWAP Columns in Hierarchical indexing

In [ ]:
df7

In [ ]:
df8=df7.set_index(['Year', 'Literacy/GDP'])
df8

In [ ]:
# Swaping the columns in Hierarchical index
df9 = df8.swaplevel('Year', 'Literacy/GDP')
df9

In [ ]:
# Swaping the columns in Hierarchical index
df9 = df9.swaplevel('Year', 'Literacy/GDP')
df9

# Crosstab in Pandas

In [ ]:
df7

In [ ]:
pd.crosstab(df7['Literacy/GDP'] , df7.Value , margins=True)

In [ ]:
# 2 way cross table
pd.crosstab(df7.Year , df7['Literacy/GDP'] , margins=True)

In [ ]:
# 3 way cross table
pd.crosstab([df7.Year , df7['Literacy/GDP']] , df7.Country, margins=True)

# Row & Column Bind

### Row Bind

In [ ]:
df8 = pd.DataFrame({'ID' :[1,2,3,4] ,  'Name' :['Asif' , 'Basit' , 'Ross' , 'John'] , 'Score' :[99 , 66 , 44 , 33]})
df8

In [ ]:
df9 = pd.DataFrame({'ID' :[5,6,7,8] ,  'Name' :['Michelle' , 'Ramiro' , 'Vignesh' , 'Damon'] , 'Score' :[78 , 54 , 77 , 87]})
df9

In [ ]:
# Row Bind with concat() function
pd.concat([df8 , df9])

In [ ]:
# Row Bind with append() function
df8.append(df9)

### Column Bind

In [ ]:
df10 = pd.DataFrame({'ID' :[1,2,3,4] , 'Name' :['Asif' , 'Basit' , 'Ross' , 'John']})
df10

In [ ]:
df11 = pd.DataFrame({'Age' :[20,30,35,40] , 'Score' :[99 , 66 , 44 , 33]})
df11

In [ ]:
pd.concat([df10,df11] , axis = 1)